### ISSUE TITLE
create UDF fail 

### ISSUE THREAD

**Issue by audaq** [WeBankFinTech/Linkis#13]
![image](https://user-images.githubusercontent.com/10127230/61884967-a8184f80-af2f-11e9-8fdb-ea6e0dca7763.png)

ERROR INFO:
{"method":null,"status":1,"message":"errCode: 52004 ,desc: You must register IOClient before you can use proxy mode.(必须先注册IOClient，才能使用代理模式) ,ip: bdpdwc010003 ,port: 12345 ,serviceKind: cloud-publicservice","data":{}}

**Comment by peacewong** [comment]
Proxy mode can be removed and fixed
