### ISSUE TITLE
[Bug] The Log Save Path Change Structure Cause Common User Not Permission

### ISSUE THREAD

**Issue by xiaojie19852006** [WeBankFinTech/Linkis#1341]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-cg-entrance

### What happened + What you expected to happen

When user execute command have the error,
![HPT7D7C20N1OLD{%SX0 UTV](https://user-images.githubusercontent.com/32708280/151518492-af1cb3ca-d8de-48a9-a56c-b4bc3ff6b1dc.jpg)

and check the public-service and entrance log,find the similar error,have no permission to the log save path

### Relevent platform

Linkis 1.0.3 

### Reproduction script

No

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by xiaojie19852006** [comment]
Check the related code,the main code in ParserUtils.generateLogPath.
I have a doubt that why change structure for the path,the new path add a new level <creator> up the <user>,and the <creator> directory set permission is 770.
the other user have no permission to view the dir;
why change the directory structure?

**Comment by xiaojie19852006** [comment]
Now,We set 777 permission for the [creator] directory;

**Comment by peacewong** [comment]
Is there a permission leak problem when set to 777?

**Comment by saLeox** [comment]
Hi, you can configue the 'wds.linkis.entrance.config.log.path=xx' in linkis-cg-entrance.properties file, it will help solve the problem.
