### ISSUE TITLE
importAndExport can not open 

### ISSUE THREAD

**Issue by audaq** [WeBankFinTech/Linkis#14]
importAndExport
![image](https://user-images.githubusercontent.com/10127230/61893459-b1f67e80-af40-11e9-9e3b-df0f3ddbf124.png)

**Comment by xtt55** [comment]
Can you take a screenshot to see the interface return? Is it a configuration problem? @audaq

**Comment by wushengyeyouya** [comment]
Please go to Scriptis to give us this issue, thank you!
