### ISSUE TITLE
ldap dn chinese garbled code

### ISSUE THREAD

**Issue by nimuyuhan** [WeBankFinTech/Linkis#143]
## Describe the bug
Configuration file ou information has been tampered with, Because the linkis-gateway  module ldap information Chinese garbled code.

## The phenomenon is as follows
OU=[AD53349]数据中台部
![image](https://user-images.githubusercontent.com/3031530/69493561-16275000-0eeb-11ea-9731-3ffe3121666f.png)

The organizational unit(ou) serves as an organizational path, If some cells are misorganized, there is no way to restrict cell organizational unit(ou).

**Comment by nimuyuhan** [comment]
I'll work on this

**Comment by peacewong** [comment]
Hello, do you mean that the Chinese in the configuration file will be garbled?

**Comment by nimuyuhan** [comment]
Yes, Thanks peacewong for helping to explain.
