### ISSUE TITLE
down  Excel gbk fail

### ISSUE THREAD

**Issue by audaq** [WeBankFinTech/Linkis#15]
![image](https://user-images.githubusercontent.com/10127230/61893564-f3872980-af40-11e9-906e-8012586e0569.png)

**Comment by xtt55** [comment]
Can I take a screenshot of the options?

**Comment by xtt55** [comment]
The screenshot shows that the result set is a table. If the download options are "excel" and "gbk", the suffix of the download file should be "xlsx".

**Comment by wushengyeyouya** [comment]
Please go to Scriptis to give us this issue, thank you!
