### ISSUE TITLE
Linkis 0.9.1 对hadoop的支持

### ISSUE THREAD

**Issue by shernupup** [WeBankFinTech/Linkis#164]
目前只hadoop CDH3以下的版本，CDH3以下的hadoop版本最高只到0.21
如果想适配更高版本的hadoop应该如何解决？roadmap中是否有对更高版本cdh支持的计划？

**Comment by peacewong** [comment]
Hello, Linkis normally does not depend on the Hadoop version, you can modify the corresponding hadoop version to compile

**Comment by shernupup** [comment]
ok,Thanks !
