### ISSUE TITLE
Linkis 0.9.2 对Flink的支持

### ISSUE THREAD

**Issue by walter211** [WeBankFinTech/Linkis#165]
如果能支持下个版本就打算内部试用推广了

**Comment by wushengyeyouya** [comment]
We have planned to achieve this feature, invite you to join us!

**Comment by Chengyanan1008** [comment]
Linkis 支持Flink了吗

**Comment by walter211** [comment]
You guys are awesome, close this cause fo https://github.com/WeBankFinTech/Linkis/issues/391
