### ISSUE TITLE
带数组的结果集，前端显示读取结果集失败

### ISSUE THREAD

**Issue by liangqilang** [WeBankFinTech/Linkis#169]
**Describe the bug**
带数组的结果集，前端显示读取结果集失败

**To Reproduce**
1. Go to 'select  SQL，结果包含数组字段'
3. See error  读取结果集失败

**Screenshots**

**Comment by peacewong** [comment]
This bug has been addressed by PR, please refer to：[72](https://github.com/WeBankFinTech/Linkis/pull/172)
