### ISSUE TITLE
精简版  install.sh 提示需要hadoop

### ISSUE THREAD

**Issue by det101** [WeBankFinTech/Linkis#170]
[root@linkies2 bin]# sh install.sh
step1:load config
Succeed to + load config
Please enter the mode selection such as: 1
 1: Lite
 2: Simple
 3: Standard

Please input the choice:1
You chose Lite installation mode
Python 3.7.0
Succeed to + execute python --version
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)
Succeed to + execute java --version
Do you want to clear Linkis table information in the database?
 1: Do not execute table-building statements
 2: Dangerous! Clear all data and rebuild the tables

Please input the choice:1
You chose not execute table-building statements
create hdfs  directory and local directory
Succeed to + create local directory
install.sh:行173: hdfs: 未找到命令
Failed to  + create hdfs directory

精简不是不需要Hadoop吗？怎么这里提示用到hdfs？

**Comment by wushengyeyouya** [comment]
We will optimize it in next release.
