### ISSUE TITLE
failed to get database

### ISSUE THREAD

**Issue by XJW777** [WeBankFinTech/Linkis#171]
<img width="403" alt="脚本联想词功能存在异常" src="https://user-images.githubusercontent.com/52568764/70202402-88522d00-1754-11ea-84bd-0117e07683c4.png">

Scriptis连不到数据库，获取数据库失败；
未获取到数据库信息，脚本联想词功能存在异常！

这个怎么解决？

**Comment by godcvcv** [comment]
请问是怎么解决的？

**Comment by XJW777** [comment]
conf/config.sh 配置好Hive元数据URL；conf/db.sh 配好对应的linkis数据库

**Comment by XJW777** [comment]
> 请问是怎么解决的？

conf/config.sh 配置好Hive元数据URL；conf/db.sh 配好对应的linkis数据库

**Comment by godcvcv** [comment]
> > 请问是怎么解决的？
> 
> conf/config.sh 配置好Hive元数据URL；conf/db.sh 配好对应的linkis数据库

我也是这么配置的，但还是报这个错。你的hadoop是CDH的吗？

**Comment by XJW777** [comment]
> > > 请问是怎么解决的？
> > 
> > 
> > conf/config.sh 配置好Hive元数据URL；conf/db.sh 配好对应的linkis数据库
> 
> 我也是这么配置的，但还是报这个错。你的hadoop是CDH的吗？

对的我也是CDH，具体的报错，你可以进社区QQ群，有人会解答。
