### ISSUE TITLE
Some Suggestions for install Linkis

### ISSUE THREAD

**Issue by jiangmingrun** [WeBankFinTech/Linkis#173]
完成Linkis在Centos7上的部署与安装，经过实际操作后，有几点不成熟的建议：
1、建议增加硬件配置（比如内存建议6GB）的说明，避免因内存过小出现JVM提示“There is insufficient memory ...”；
2、建议增加对expect依赖的说明~~install.sh中有使用expect相关命令。
3、对于单机版本部署时，建议还是进行“SSH免密配置”，以避免在部署过程中不断输入密码确认。
4、执行linkis_ddl.sql的时候提示545行错误（猜测是MYSQL初始化字符集设置的问题）。建议将这行注释中文改为英文，与之前的语句统一。

======
安装环境：
Centos7(Linux 3.10.0-1062.7.1.e17.x86_64),
JDK(1.8.0._232),
Python(3.6.8),
Mysql(5.6.46),
Hadoop(2.7.0),
Hive(1.2.2),
Spark(2.4.4)

**Comment by wushengyeyouya** [comment]
Thanks very much. We will optimize it in next release.

**Comment by peacewong** [comment]
Hello, we have optimized
