### ISSUE TITLE
how to use JDBC,is there some document

### ISSUE THREAD

**Issue by wenfang6** [WeBankFinTech/Linkis#177]
**Describe the bug**
how can i  use jdbc to connect linkis
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by wushengyeyouya** [comment]
We will add and upload to the Wiki soon

**Comment by peacewong** [comment]
Hello, you can refer to the JDBC driver documentation: [jdbc driver](https://github.com/WeBankFinTech/Linkis/wiki/%E9%80%9A%E8%BF%87JDBC%E8%BF%9E%E6%8E%A5Linkis)
