### ISSUE TITLE
use scriptis exectue "create database xxxx",scriptis not prompt,but log show no permission.not friently

### ISSUE THREAD

**Issue by xccoder** [WeBankFinTech/Linkis#179]
probelem descripe：ource={scriptPath=sql}, executeApplicationName=spark, umUser=root, params={variable={}, configuration={special={}, runtime={}, startup={}}}}
2019-12-10 09:21:25.511 ERROR [WebSocket-Server-Event-ListenerBus-Thread-0] com.webank.wedatasphere.linkis.entrance.EntranceWebSocketService 72 apply - error code(错误码): 20051, error message(错误信息): sql code check failed, reason is Sorry, you have no permission to create database. com.webank.wedatasphere.linkis.entrance.interceptor.exception.CodeCheckException: errCode: 20051 ,desc: sql code check failed, reason is Sorry, you have no permission to create database ,ip: di124 ,port: 10002 ,serviceKind: sparkEntrance

use scriptis exectue "create database xxxx",scriptis not prompt,but log show no permission.not friently(尝试着使用scriptis去执行创建数据库的语句，执行没有任何进度
提示，也没有报错。但是去看日志报了没权限。这个没有日志提示容易让人产生困惑)

**Comment by peacewong** [comment]
Normally there should be these logs：
![image](https://user-images.githubusercontent.com/11496700/70492242-b82b7700-1b3e-11ea-9080-7f124ed51d87.png)
Hello, can you look at the relevant log4j package under your lib package? linkis-ujes-spark-enginemanager/lib/
```
log4j-1.2.17.jar
log4j-api-2.10.0.jar
log4j-core-2.10.0.jar
log4j-jul-2.10.0.jar
log4j-slf4j-impl-2.10.0.jar
spring-boot-starter-log4j2-2.0.3.RELEASE.jar
```

**Comment by xccoder** [comment]
under  linkis-ujes-spark-enginemanager/lib/, include above all jar。
i analysis open source linkis not check creata database permission,by check key word ‘create database’ interceptor
![Snipaste_2019-12-11_13-43-20](https://user-images.githubusercontent.com/16348865/70594849-acae7d80-1c1c-11ea-8641-d655231e4766.png)
![Snipaste_2019-12-11_13-44-25](https://user-images.githubusercontent.com/16348865/70594854-afa96e00-1c1c-11ea-8ebd-7035cc8a01dd.png)
![Snipaste_2019-12-11_13-44-37](https://user-images.githubusercontent.com/16348865/70594857-b1733180-1c1c-11ea-93aa-55b2c03f523a.png)

process banber: job status failed is reasonable

**Comment by peacewong** [comment]
No, my test is on the open source version.Can you help put all the lib packages up and look

**Comment by peacewong** [comment]
Hello, we have optimized the package
