### ISSUE TITLE
引擎和资源管理器如何注册

### ISSUE THREAD

**Issue by zhangchao930216** [WeBankFinTech/Linkis#182]
比如 HIVEENTRANCE 和HIVEENGINEMANAGER 和RESOURCEMANAGER的关系
ENGINE 是如何注册到RESOURCEMANAGER里 
何时写入linkis_em_meta_data  这张表的？

**Comment by peacewong** [comment]
Hello you can refer to this article: 
https://github.com/WeBankFinTech/Linkis/wiki/Linkis-RM%E8%AE%BE%E8%AE%A1%E6%96%87%E6%A1%A3
