### ISSUE TITLE
mv: 无法获取"linkis-gateway"

### ISSUE THREAD

**Issue by det101** [WeBankFinTech/Linkis#186]
linkis-gateway-step1: create dir
linkis-gateway-step2:copy install package
linkis-gateway.zip                                                                          100%  101MB  23.6MB/s   00:04
Succeed to + copy linkis-gateway.zip
mv: 无法获取"linkis-gateway" 的文件状态(stat): 没有那个文件或目录
Succeed to + unzip linkis-gateway.zip
linkis-gateway-step3:subsitution conf
Succeed to + subsitution conf of linkis-gateway
linkis-gateway-step4:update linkis conf
Succeed to + subsitution linkis.properties of linkis-gateway
<----------------linkis-gateway:end------------------->

**Comment by wushengyeyouya** [comment]
It's just a warning, please ignore it.
