### ISSUE TITLE
how to Configuration LADP

### ISSUE THREAD

**Issue by audaq** [WeBankFinTech/Linkis#19]
how to Configuration LADP
![image](https://user-images.githubusercontent.com/10127230/61938208-24a83e00-afc3-11e9-9ec9-63188070e71f.png)

**Comment by yangzhiyue** [comment]
Thanks for your issue. LDAP is the default way in our company for logging in. If the organization you work at uses the same way for logging in, you can just set your ldap url in config.sh. If you just wanna try Linkis, we have set a special user - hadoop (password is hadoop as well).

**Comment by wushengyeyouya** [comment]
LDAP is supported by default, please take a look at the deployment documentation, Thanks!
