### ISSUE TITLE
DownloadAction未进行异常处理，导致异常信息写入数据流

### ISSUE THREAD

**Issue by liangqilang** [WeBankFinTech/Linkis#190]
**Describe the bug**
  DownloadAction未进行异常处理，导致异常信息写入数据流
**To Reproduce**
1.   DownloadAction  def write(inputStream: InputStream): Unit 如果服务端抛异常该方法会将异常数据写入数据流

**Comment by peacewong** [comment]
Thank you for fixing this issue，[PR 27](https://github.com/WeBankFinTech/Linkis/pull/225)
