### ISSUE TITLE
Compile ERROR

### ISSUE THREAD

**Issue by audaq** [WeBankFinTech/Linkis#2]
mvn -N install
[INFO] Scanning for projects...
Downloading: http://maven.oschina.net/content/groups/public/org/springframework/
cloud/spring-cloud-dependencies/Finchley.RELEASE/spring-cloud-dependencies-Finch
ley.RELEASE.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[WARNING] 'build.pluginManagement.plugins.plugin.(groupId:artifactId)' must be u
nique but found duplicate declaration of plugin org.apache.maven.plugins:maven-d
eploy-plugin @ line 245, column 25
[ERROR] Non-resolvable import POM: Could not transfer artifact org.springframewo
rk.cloud:spring-cloud-dependencies:pom:Finchley.RELEASE from/to nexus-osc (http:
//maven.oschina.net/content/groups/public/): maven.oschina.net @ line 127, colum
n 25
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.webank.wedatasphere.linkis:linkis:0.5.0 (C:\Users\neil
jianliu\Linkis\pom.xml) has 1 error
[ERROR]     Non-resolvable import POM: Could not transfer artifact org.springfra
mework.cloud:spring-cloud-dependencies:pom:Finchley.RELEASE from/to nexus-osc (h
ttp://maven.oschina.net/content/groups/public/): maven.oschina.net @ line 127, c
olumn 25: Unknown host maven.oschina.net -> [Help 2]
[ERROR]

**Comment by liuyou2** [comment]
Check that your maven Settings are correct
