### ISSUE TITLE
The linkis_ddl.sql  file of linkis0.9 has a syntax error！

### ISSUE THREAD

**Issue by cong520** [WeBankFinTech/Linkis#205]
On mysql5.7,Space required after comment。
![image](https://user-images.githubusercontent.com/18363125/70873107-fc0ef800-1fe6-11ea-8cd0-e4b562ebbad4.png)
![image](https://user-images.githubusercontent.com/18363125/70873114-0cbf6e00-1fe7-11ea-9401-11cd8df5b3e7.png)

**Comment by weipengffk** [comment]
我也碰到这个问题了，加个空白就好了。这是啥原因

**Comment by wushengyeyouya** [comment]
Possibly caused by incompatible versions, we will fix it in the next release

**Comment by peacewong** [comment]
The issue has been fixed
