### ISSUE TITLE
kerberos support

### ISSUE THREAD

**Issue by moranrr** [WeBankFinTech/Linkis#212]
Now engine does not support kerberos.  hope to add the integration with kerberos.

**Comment by peacewong** [comment]
Hello, linkis supports kerberos, you can refer to [FAQ](https://github.com/WeBankFinTech/Linkis/wiki/%E9%83%A8%E7%BD%B2%E5%92%8C%E7%BC%96%E8%AF%91%E9%97%AE%E9%A2%98%E6%80%BB%E7%BB%93), Question 15

**Comment by moranrr** [comment]
> Hello, linkis supports kerberos, you can refer to [FAQ](https://github.com/WeBankFinTech/Linkis/wiki/%E9%83%A8%E7%BD%B2%E5%92%8C%E7%BC%96%E8%AF%91%E9%97%AE%E9%A2%98%E6%80%BB%E7%BB%93), Question 15

filesystem is support kerberos. but engine like hive or spark not support!

**Comment by wushengyeyouya** [comment]
The kerberos support for engine is depended on your cluster kinit policy.
