### ISSUE TITLE
0.91 hql执行获取结果集失败

### ISSUE THREAD

**Issue by Drizzlevivi** [WeBankFinTech/Linkis#220]
**Describe the bug**
hdfs路径配置有 Nameservice时 ，在调用/api/rest_j/v1/filesystem/getDirFileTrees接口时，返回的结果会去掉Nameservice。

**To Reproduce**
HDFS配置如下
### User's root hdfs path
HDFS_USER_ROOT_PATH=hdfs://nameservice1:8020/tmp/linkis ##hdfs:// required
### Path to store job ResultSet??<9a>file or hdfs path
RESULT_SET_ROOT_PATH=hdfs://nameservice1:8020/tmp/linkis

**Comment by wushengyeyouya** [comment]
If there is no Nameservice in HDFS path, will the file read error?
