### ISSUE TITLE
代码里面使用比较老的jackson包，hadoop 2.6.0-cdh5.7.6 环境下编译失败（The old Jackson package is used in the code）

### ISSUE THREAD

**Issue by wForget** [WeBankFinTech/Linkis#226]
**Is your feature request related to a problem? Please describe.**
代码中使用了 org.codehaus.jackson.JsonNode 等比较老的包，在 hadoop 2.6.0-cdh5.7.6 中依赖 jackson-core-asl 的版本是 1.8.8，该版本中 JsonNode 没有 asText 方法，导致部分模块编译出错。

**Describe the solution you'd like**
建议使用 com.fasterxml.jackson.core 的 jackson 包

**Describe alternatives you've considered**
no

**Additional context**
no

---

**Is your feature request related to a problem? Please describe.**
Some older packages such as org.codehaus.jackson.JsonNode are used in the code. The version that relies on jackson-core-asl in Hadoop 2.6.0-cdh5.7.6 is 1.8.8. In this version, JsonNode has no astext method, resulting in some module compilation errors.

**Describe the solution you'd like**
The Jackson package of com.fasterxml.jackson.core is recommended

**Describe alternatives you've considered**
no

**Additional context**
no

**Comment by wForget** [comment]
临时方案：
在 linkis-hadoop-common 模块的 hadoop 相关依赖中排除老的包
```
<exclusion>
	<groupId>org.codehaus.jackson</groupId>
	<artifactId>jackson-mapper-asl</artifactId>
</exclusion>
<exclusion>
	<groupId>org.codehaus.jackson</groupId>
	<artifactId>jackson-core-asl</artifactId>
</exclusion>
<exclusion>
	<groupId>org.codehaus.jackson</groupId>
	<artifactId>jackson-jaxrs</artifactId>
</exclusion>
<exclusion>
	<groupId>org.codehaus.jackson</groupId>
	<artifactId>jackson-xc</artifactId>
</exclusion>
```
再加上 1.9.2 版本的依赖
```
<dependency>
	<groupId>org.codehaus.jackson</groupId>
	<artifactId>jackson-mapper-asl</artifactId>
	<version>1.9.2</version>
</dependency>
<dependency>
	<groupId>org.codehaus.jackson</groupId>
	<artifactId>jackson-core-asl</artifactId>
	<version>1.9.2</version>
</dependency>
<dependency>
	<groupId>org.codehaus.jackson</groupId>
	<artifactId>jackson-jaxrs</artifactId>
	<version>1.9.2</version>
</dependency>
<dependency>
	<groupId>org.codehaus.jackson</groupId>
	<artifactId>jackson-xc</artifactId>
	<version>1.9.2</version>
</dependency>
```

**Comment by peacewong** [comment]
It looks like a problem. We'll fix it
