### ISSUE TITLE
hadoop 2.6.0-cdh5.7.6 环境需要排除 jasper-compiler、jasper-runtime

### ISSUE THREAD

**Issue by wForget** [WeBankFinTech/Linkis#229]
**Is your feature request related to a problem? Please describe.**
hadoop版本为2.6.0-cdh5.7.6，启动微服务时不会扫描 wds.linkis.server.restful.scan.packages 配置的 package，导致接口 404

**Describe the solution you'd like**
~~在 linkis-hadoop-common 模块的 hadoop-common、hadoop-hdfs 依赖中排除 jasper-compiler、jasper-runtime 包~~
```
<exclusion>
	<artifactId>jasper-compiler</artifactId>
	<groupId>tomcat</groupId>
</exclusion>
<exclusion>
	<artifactId>jasper-runtime</artifactId>
	<groupId>tomcat</groupId>
</exclusion>
```

排除 hadoop 依赖中的 jasper 包，还是没有办法排除干净，所以在 \Linkis\assembly\public-module\src\main\assembly\distribution.xml 文件中进行排除

**Describe alternatives you've considered**
no

**Additional context**
no

**Comment by wForget** [comment]
没有排除依赖时的日志：
![image](https://user-images.githubusercontent.com/17894939/71410498-7e9b5580-2680-11ea-8cde-1aebbdb70313.png)
排除依赖时的日志：
![image](https://user-images.githubusercontent.com/17894939/71410762-87d8f200-2681-11ea-8294-9d3afd032053.png)

**Comment by peacewong** [comment]
Thank you, this is a bug in the CDH version. We will exclude jasper related packages in the public-module.
