### ISSUE TITLE
install.sh 安装，修改 linkis-publicservice 配置文件（gateway.port）失败

### ISSUE THREAD

**Issue by muicoder** [WeBankFinTech/Linkis#236]
**Describe the bug**
这个文件里的wds.linkis.gateway.port=9001 不会通过install修改

**To Reproduce**
1. 执行完 install.sh 安装脚本
2. 查看linkis-publicservice/conf/linkis.properties
3. 发现仍然是wds.linkis.gateway.port=9001

**Comment by peacewong** [comment]
Thanks, this is a bug and we will fix it
