### ISSUE TITLE
计算引擎错误智能重试

### ISSUE THREAD

**Issue by wenfang6** [WeBankFinTech/Linkis#237]
想了解一下计算引擎错误智能重试的设计思想，可否详细解释一下呢，谢谢

**Comment by peacewong** [comment]
You can get the retry logic by looking at where DWCRetryException and WarnException are used.For example, when requesting the engine:
![image](https://user-images.githubusercontent.com/11496700/71617153-c2e4a380-2bf4-11ea-91c5-e1ed7fcfbb22.png)

**Comment by wenfang6** [comment]
Thank you!
