### ISSUE TITLE
Need to support the function of data exchange between hive and excel

### ISSUE THREAD

**Issue by patinousward** [WeBankFinTech/Linkis#25]

**Comment by wushengyeyouya** [comment]
Can you give us more detail information about this feature?

**Comment by wushengyeyouya** [comment]
Thanks for contributing code. But can you write some description to us? Thanks again!!!

**Comment by patinousward** [comment]
> Can you give us more detail information about this feature?

spark-excel features：
1.user can import excel into hive form local filesystem and hdfs by scala scripts,user can specify the data type（double，bigint..）
2.export excel is also easy by using this module
3.it runs good in an environment of big data
user can add the dependency  when they need it

**Comment by wushengyeyouya** [comment]
A great plugin, can you tell me about your company's application scenarios, and why would you consider doing such a plugin?

**Comment by wushengyeyouya** [comment]
Hi, please add my WeChat: wushengyeyy, let's talk more.
Thanks!

**Comment by patinousward** [comment]
> Hi, please add my WeChat: wushengyeyy, let's talk more.
> Thanks!

No problem, my honor！
