### ISSUE TITLE
执行linkis中的install.sh报错

### ISSUE THREAD

**Issue by itwhat126** [WeBankFinTech/Linkis#262]
bin/install.sh: 20: bin/install.sh: source: not found
bin/install.sh: 28: bin/install.sh: [[: not found
bin/install.sh: 30: bin/install.sh: [[: not found
bin/install.sh: 33: bin/install.sh: [[: not found
bin/install.sh: 36: bin/install.sh: [[: not found
bin/install.sh: 39: bin/install.sh: [[: not found
bin/install.sh: 42: bin/install.sh: [[: not found
Operating system unknown, please tell us(submit issue) for better service

ubuntu18.04系统

**Comment by fy403** [comment]
代码对于标准bash而言没有错，因为[Ubuntu](https://so.csdn.net/so/search?q=Ubuntu&spm=1001.2101.3001.7020)/Debian为了加快开机速度，用dash代替了传统的bash，是dash在捣鬼，解决方法就是取消dash。

解决：

1） sudo dpkg-reconfigure dash       在选择项中选No，搞定了！
