### ISSUE TITLE
linkis的install.sh在ubuntu中存在兼容问题

### ISSUE THREAD

**Issue by itwhat126** [WeBankFinTech/Linkis#263]
1、ubuntu中执行该脚本要用bash命令而不是sh
2、脚本里似乎需要使用yum命令，而该命令在ubuntu系统中并不是默认存在的
3、同上脚本里需要dos2unix，ubuntu似乎也不支持。
4、似乎ubuntu在~目录下并不存在.bash_profile

暂时在ubuntu发现以上问题，希望开发团队可以测试下ubuntu兼容性，谢谢~

**Comment by peacewong** [comment]
Question is duplicated with # 264, closed now
