### ISSUE TITLE
Hive 2.3.6适配问题

### ISSUE THREAD

**Issue by jiaorenyu** [WeBankFinTech/Linkis#270]
我们的环境：

> 平台环境：ResourceManager version:2.6.1-adh2.4.4, Hadoop version:2.6.1-adh2.4.4
> Spark版本：2.4.4
> Hive版本：2.3.6

使用的Linkis版本：0.9.2

安装精简版的已经测试通过，可以使用scripts提交python脚本执行了，现在要安装标准版。

在编译时修改pom.xml文件如下：
```
        <hadoop.version>2.6.1</hadoop.version>
        <hive.version>2.3.6</hive.version>
```

没有找到修改spark版本的地方。。。

编译没有报错，按照wiki给出的方式执行，如下：

```
mvn -N  install
mvn clean install
```

把jar包： `wedatasphere-linkis-0.9.2-dist.tar.gz` 上传上去后安装启动，
发现启动linkis-metadata时出现异常如下：

![屏幕快照 2020-01-17 上午10 36 35](https://user-images.githubusercontent.com/16011475/72579880-5b796400-3915-11ea-8a90-a6ca3710bef9.png)

查看linkis-metadata中有关log的jar包，如下：
![屏幕快照 2020-01-17 上午10 39 09](https://user-images.githubusercontent.com/16011475/72579978-9d0a0f00-3915-11ea-8a20-dcd637cb09ec.png)

查看module下有关log的jar包如下：

![屏幕快照 2020-01-17 上午10 40 03](https://user-images.githubusercontent.com/16011475/72580025-bd39ce00-3915-11ea-986a-f4a095628a80.png)

两者的版本号不一致，曾尝试把两者的log4j版本都统一成2.6.2或2.10.0都没有成功。

**Comment by peacewong** [comment]
Linkis will be compatible with multiple versions of hive in subsequent releases

**Comment by jiaorenyu** [comment]
> Linkis will be compatible with multiple versions of hive in subsequent releases

Thanks
