### ISSUE TITLE
The hive engine is not compatible with hive 3.1.2

### ISSUE THREAD

**Issue by wForget** [WeBankFinTech/Linkis#277]
**Describe the bug**
The hive engine is not compatible with hive 3.1.2
1. CommandNeedRetryException removed in 3.1.2 of hive.
2. Driver extend from IDriver in 3.1.2 of hive.

**Desktop (please complete the following information):**
hive 3.1.2

**Comment by peacewong** [comment]
Yes, compatibility with the hive version is an important feature
