### ISSUE TITLE
安装后运行，gateway中存在netty的jar报冲突

### ISSUE THREAD

**Issue by MZ848083** [WeBankFinTech/Linkis#28]
打包运行时，gateway服务启动失败。发现netty-all包版本和其他不一致，移除后，服务正常启动。估计是其他依赖引入的netty-all包，请排查之后排除相关包

**Comment by liuyou2** [comment]
This is a jar conflict problem that requires the netty-all dependency to be removed from the gateway

**Comment by peacewong** [comment]
This issue has been fixed
