### ISSUE TITLE
查看任务运行日志报日志文件不存在

### ISSUE THREAD

**Issue by bingfeng2004** [WeBankFinTech/Linkis#286]
使用的是linkis-0.9.3版本，linkis的服务部署在多台机器上
执行了HQL或Spark sql，查看日志会提示找不到日志文件，而这个日志文件在引擎所在的服务器上是可以找到，经分析是由于HIVE或Spark的引擎服务和publicservice服务不在同一台机器上导致的，请问这些服务只能都部署在一台机器上，分布式不支持？

**Comment by peacewong** [comment]
Hello, we recommend the following:
1. Use our IO proxy service, which is not installed by default in the Storage / pesIO module
2. Use Linux's nfs as a shared directory
3. Deploy the publicservice and theance service on one machine
