### ISSUE TITLE
Please provide Metadata Management Common Module.

### ISSUE THREAD

**Issue by Alexkun** [WeBankFinTech/Linkis#302]
**Describe the solution you'd like**
I think Metada Management should be enhanced. Please provide Metadata Management Common Module for uniform use of metadata service. It defines the uniform interface of metadata service, connection cache, information structure and the basic implement of service and rpc receiver.

**Describe alternatives you've considered**
no

**Additional context**
no

**Comment by yangzhiyue** [comment]
thanks it is closed in #305
