### ISSUE TITLE
spark config bug

### ISSUE THREAD

**Issue by mi1049971930** [WeBankFinTech/Linkis#321]
linkis控制台->设置->数据开发spark->spark资源设置  该配置在实际使用中并未生效，页面修改保存后，数据库中并未修改

**Comment by chinaboyll** [comment]
mysql执行以下结果，截图查看一下？
SELECT         bdck.id AS `key_id`,         bdck.`key`,         bdck.description,         bdck.`name`,         bdck.application_id AS `creator_id`,         bdck.default_value,         bdck.validate_type,         bdck.validate_range,         bdck.is_advanced,         bdck.is_hidden,         bdck.level,         bdcku.id AS `value_id`,         bdcku.application_id,         bdcku.user_name,         bdcku.`value`         FROM linkis_config_key bdck         LEFT JOIN linkis_config_key_user bdcku         ON bdck.id=bdcku.key_id where bdcku.application_id=2
