### ISSUE TITLE
Configuration issue with linkis-storage module

### ISSUE THREAD

**Issue by oldbelvey** [WeBankFinTech/Linkis#330]
Class ： com.webank.wedatasphere.linkis.storage.utils.StorageConfiguration
Original:
![image](https://user-images.githubusercontent.com/22738056/77037437-4d66c300-69ec-11ea-8827-5ef7a301d208.png)

Suggestion：
![image](https://user-images.githubusercontent.com/22738056/77037538-8e5ed780-69ec-11ea-99a5-9e0924491e78.png)

**Comment by peacewong** [comment]
Thank you, can you help us with a PR fix

**Comment by oldbelvey** [comment]
ok, u can review it at   https://github.com/WeBankFinTech/Linkis/pull/331
