### ISSUE TITLE
Script execution outputs real-time logs to the front end

### ISSUE THREAD

**Issue by bingfeng2004** [WeBankFinTech/Linkis#335]
We were using linkis, front end to submit a script execution, can only wait for tasks to view the log information, and through the log interface to get the log does not contain the detailed information in the process of execution, execution of the script users can't through the log analysis the cause of the failure, only through the back-end engine service in the log to see the error information.
      What can I do to get real-time logs and detailed error logs in real time?

**Comment by peacewong** [comment]
Hello, this is to reduce unnecessary logs for the user. When the task fails, only the logs of the ERROR level are pushed. You can modify the push level by modifying log4j2
