### ISSUE TITLE
Hive engine can't work property

### ISSUE THREAD

**Issue by jkl0898** [WeBankFinTech/Linkis#340]
**Describe the bug**

1. SET export PS1='<\u@\h $PWD \$>' to .bashrc of user's environment for pretty show.
2. Running the hql on dss which  failed due to timeout. 

**To Reproduce**
1. Go to 'dss'
2. Click on 'hql excute'
3. Scroll down to 'waiting for result'
4. See error and not result

**Expected behavior**

Would like to get the result from the hql.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: CentOS Linux release 7.7.1908
 - Browser  chrome 
 - Version wedatasphere-dss-web-0.7.0  wedatasphere-linkis-0.9.3

**Smartphone (please complete the following information):**
 - Device: None
 - OS: None
 - Browser None
 - Version None

**Additional context**
Optimize the logic of  script rootScript.sh to make dss  more reliable for customer.
![image](https://user-images.githubusercontent.com/14175165/78740031-33cff000-7988-11ea-8c38-54c45da30755.png)

**Comment by peacewong** [comment]
Ok, this issue has been fixed
