### ISSUE TITLE
修改hadoop版本之后重新编译linkis、dss，但DSS编译不成功，出现以下错误

### ISSUE THREAD

**Issue by jhj-123** [WeBankFinTech/Linkis#341]
[INFO]
[INFO] ------------< com.webank.wedatasphere.dss:dss-application >-------------
[INFO] Building dss-application 0.7.0                                    [6/19]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ dss-application ---
[INFO] Deleting /root/jhj/DataSphereStudio-master/dss-application/target
[INFO]
[INFO] --- scala-maven-plugin:3.2.2:compile (default-cli) @ dss-application ---
[WARNING]  Expected all dependencies to require Scala version: 2.11.8
[WARNING]  com.webank.wedatasphere.linkis:linkis-common:0.9.3 requires scala version: 2.11.8
[WARNING]  com.webank.wedatasphere.linkis:linkis-common:0.9.3 requires scala version: 2.11.8
[WARNING]  com.webank.wedatasphere.linkis:linkis-common:0.9.3 requires scala version: 2.11.8
[WARNING]  com.webank.wedatasphere.dss:dss-common:0.7.0 requires scala version: 2.11.8
[WARNING]  com.webank.wedatasphere.dss:dss-common:0.7.0 requires scala version: 2.11.8
[WARNING]  com.webank.wedatasphere.dss:dss-common:0.7.0 requires scala version: 2.11.8
[WARNING]  com.webank.wedatasphere.dss:dss-appjoint-core:0.7.0 requires scala version: 2.11.8
[WARNING]  com.webank.wedatasphere.dss:dss-appjoint-core:0.7.0 requires scala version: 2.11.8
[WARNING]  com.webank.wedatasphere.dss:dss-appjoint-core:0.7.0 requires scala version: 2.11.8
[WARNING]  com.webank.wedatasphere.dss:dss-appjoint-loader:0.7.0 requires scala version: 2.11.8
[WARNING]  com.webank.wedatasphere.dss:dss-appjoint-loader:0.7.0 requires scala version: 2.11.8
[WARNING]  com.webank.wedatasphere.dss:dss-appjoint-loader:0.7.0 requires scala version: 2.11.8
[WARNING]  com.webank.wedatasphere.dss:dss-application:0.7.0 requires scala version: 2.11.8
[WARNING]  com.webank.wedatasphere.dss:dss-application:0.7.0 requires scala version: 2.11.8
[WARNING]  org.scala-lang:scala-compiler:2.11.8 requires scala version: 2.11.8
[WARNING]  org.scala-lang.modules:scala-xml_2.11:1.0.4 requires scala version: 2.11.4
[WARNING] Multiple versions of scala libraries detected!
[WARNING] Zinc server is not available at port 3030 - reverting to normal incremental compile
[INFO] Using incremental compilation
[INFO] Compiling 23 Java sources to /root/jhj/DataSphereStudio-master/dss-application/target/classes...
[ERROR] /root/jhj/DataSphereStudio-master/dss-application/src/main/java/com/webank/wedatasphere/dss/application/service/impl/ApplicationServiceImpl.java:29: 错误: 程序包org.apache.htrace.fasterxml.jackson.databind不存在
[ERROR] import org.apache.htrace.fasterxml.jackson.databind.JavaType;
[ERROR]                                                    ^
[ERROR] /root/jhj/DataSphereStudio-master/dss-application/src/main/java/com/webank/wedatasphere/dss/application/service/impl/ApplicationServiceImpl.java:30: 错误: 程序包org.apache.htrace.fasterxml.jackson.databind不存在
[ERROR] import org.apache.htrace.fasterxml.jackson.databind.ObjectMapper;
[ERROR]                                                    ^
[ERROR] 2 个错误
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for dss 0.7.0:
[INFO]
[INFO] dss ................................................ SUCCESS [  0.493 s]
[INFO] dss-common ......................................... SUCCESS [ 11.726 s]
[INFO] dss-appjoint-auth .................................. SUCCESS [  8.880 s]
[INFO] dss-appjoint-core .................................. SUCCESS [ 10.917 s]
[INFO] dss-appjoint-loader ................................ SUCCESS [  8.073 s]
[INFO] dss-application .................................... FAILURE [  3.538 s]
[INFO] dss-scheduler-appjoint-core ........................ SKIPPED
[INFO] dss-linkis-node-execution .......................... SKIPPED
[INFO] dss-flow-execution-entrance ........................ SKIPPED
[INFO] dss-azkaban-scheduler-appjoint ..................... SKIPPED
[INFO] dss-server ......................................... SKIPPED
[INFO] dss-visualis-appjoint .............................. SKIPPED
[INFO] dss-qualitis-appjoint .............................. SKIPPED
[INFO] dss-eventchecker-appjoint .......................... SKIPPED
[INFO] dss-datachecker-appjoint ........................... SKIPPED
[INFO] dss-sendmail-appjoint-core ......................... SKIPPED
[INFO] linkis-jobtype ..................................... SKIPPED
[INFO] linkis-appjoint-entrance ........................... SKIPPED
[INFO] dss-assembly ....................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  51.570 s
[INFO] Finished at: 2020-04-10T14:32:38+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.2:compile (default-cli) on project dss-application: Execution default-cli of goal net.alchim31.maven:scala-maven-plugin:3.2.2:compile failed.: CompileFailed -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :dss-application

**Comment by Alexkun** [comment]
Have you tried "mvn scala:compile install -rf :dss-application ", and you should ensure that the version of scala is  2.11.x

**Comment by jhj-123** [comment]
这个命令  我试了，还是不行，我scala  是 2.11.8的

**Comment by jhj-123** [comment]
> 您是否尝试过“ mvn scala：compile install -rf：dss-application”，并且应确保scala的版本为2.11.x
