### ISSUE TITLE
scriptis加载问题

### ISSUE THREAD

**Issue by 77954309** [WeBankFinTech/Linkis#355]
我把workspace存储到hdfs中后，我看每次加载，跟以前不一样了，脚本工作台没有保存，配置按键了，![image](https://user-images.githubusercontent.com/16789827/80302434-99bbd480-87dc-11ea-8ef1-b9b316bcc988.png)

原来工作空间存储本地，有保存和配置
![image](https://user-images.githubusercontent.com/16789827/80302471-d8518f00-87dc-11ea-94ec-29577344abcf.png)

**Comment by 77954309** [comment]
这个是版本问题。前端拦截了

**Comment by peacewong** [comment]
Hello, has this issue been resolved?

**Comment by 77954309** [comment]
版本有问题，换了其他方案，不用hdfs作为workspace的目录

**Comment by 77954309** [comment]
> Hello, has this issue been resolved?
换了方案，不用hdfs作为workspace.

**Comment by 77954309** [comment]
> Hello, has this issue been resolved?

换了方案，不用hdfs作为workspace.
