### ISSUE TITLE
hive progress bug

### ISSUE THREAD

**Issue by tinyRookie** [WeBankFinTech/Linkis#36]
Hi, I have set up  your system in my cluster, and it can run hive sql. It works awesome. But sometimes it is not right showing the hive mapreduce progress as pic shows below, can you fix it?
![image](https://user-images.githubusercontent.com/3347292/62443958-d3503980-b78e-11e9-84f0-262a6ee2419d.png)

**Comment by yangzhiyue** [comment]
Hi can you tell me what your hive version is? It may raise some problems in the environment differing from ours.

**Comment by tinyRookie** [comment]
Hello, hive version is hive-1.1.0-cdh5.9.2, hadoop version is hadoop2.6.0-cdh5.9.2

**Comment by yangzhiyue** [comment]
I have solved this  problem
