### ISSUE TITLE
Linkis0.11.0 community communication(Linkis0.11.0版本社区交流)

### ISSUE THREAD

**Issue by wForget** [WeBankFinTech/Linkis#364]
## Linkis0.11.0 community communication

Linkis 0.11.0 is an important version led by MobTech.

This version mainly provides the following features：

+ Presto engine support
+ Elasticsearch engine support
+ Support spark cluster mode
+ Fix multiple bugs

### The first development communication (2020-04-29)

This communication mainly discusses the general implementation ideas of Presto engine and ES engine. Related issues are discussed as follows:

1. How to configure multiple data sources?
With the unified data source management function, you can select the corresponding data source on the right side of the script and pass it to engine through the runtime parameter.

2. Es and presto permission control?
Es adopts the permission control of user name and password. Presto does not support the way of account password at this stage, so it only implements the interface temporarily.

3. Log / Progress / ResultSet
Table result set is used for structured data, and txt result set is used for other types.
Logs need to be printed with health and error messages.
Es print the progress of SQL segmentation, and presto needs to print the progress of running.

4. About engine concurrency control
Both es and presto submit tasks through restful, Es needs to support multi-user concurrency, and use es URL to cache restclient, Presto supports multi-user concurrency, but it is recommended to start a new engine if the cluster is different.

#### MobTech Works

1. Complete Presto engine development.
2. Complete Es engine development.

#### WeBank Works

1. Assist MobTech related personnel to complete the development work.
2. Support of publishing data source function.
3. Release context function of linkis and DSS, and fix PR of multiple bugs.

#### About how to release the version

1. It will create projects in GitHub, build a version of linkis 0.11.0, and add the details of the function version first
2. Establish a branch of dev-0.11.0, submit PR, and review for consolidation
3. Issue needs to be mentioned first, and the discussion points need to be fed back to issue

### The second development communication (2020-05-09)

This communication mainly determines the specific implementation of Presto engine and ES engine, and adjusts the architecture discussed last time and the determination of some details. Related issues are discussed as follows:

1. Adopt the implementation of entrance
Using the enterprise EM engine mode, RM can't achieve complete resource control now, and can't control the concurrency of ES. If more than one entrance is started, the concurrency of users can't be controlled.

2. The resource control of concurrency and single query supported by the entrance
Register the resource (instanceresource / prestoresource) when the entrance is started, and implement the new EnginereQuester to request the resource from the ResourceManager when the EntranceEngine is created. After the execution, close the EntranceEngine and release the resource.

3. Data source module combination
In the first phase, only one data source can be configured in the management console. The user needs to configure URL link and DatasourceName. In the second phase, the service of a separate data source module supports

4. The entrance environment is isolated and compatible with multiple environments
In the gateway, the mapping between the cache environment and the entrance is done, and a new ruler is added for forwarding to realize the isolation of the environment. Consistency needs to be considered when maintaining the mapping in gateway. In order to facilitate the use of users, we need to provide multi environment support.

---

## Linkis0.11.0版本社区交流

Linkis0.11.0版本是由 MobTech 主导完成的一个重要版本。

该版本主要提供以下特性：

+ 支持 Presto 引擎
+ 支持 ElasticSearch 引擎
+ 支持 Spark Cluster 模式
+ 修复多个bug

### 第一次开发交流（2020-04-29）

此次交流主要讨论 Presto 引擎和 ES 引擎的大致实现思路。相关问题讨论如下：

1. 如何配置多数据源？
采用统一的数据源管理功能，在脚本右侧配置可以选择对应的数据源并通过 runtime 参数传递给 engine

2. ES 和 Presto 权限控制？
ES 采用用户名和密码的权限控制，Presto 由于现阶段不支持帐号密码的方式，暂时只实现接口。

3. 日志/进度/结果集
如果是结构化的数据采用Table结果集，如果是其他类型采用TXT结果集
日志需要打印运行状况，和错误提示
进度ES打印SQL切分的进度、Presto需要打印运行的进度

4. 关于引擎并发控制
ES和Presto因为都是底层通过Restful进行任务的提交
ES需要支持多用户的并发，通过ES URL来进行restClient缓存
Presto支持多用户并发但是如果集群不一样建议启动新的引擎

#### MobTech 工作

1. 完成 Presto 引擎开发
2. 完成 Es 引擎开发

#### 微众工作

1. 协助 MobTech 相关人员完成开发工作
2. 发布数据源功能的支持
3. 发布Linkis和DSS的上下文功能和多个bug修复PR

#### 关于怎么发布版本

1. 会在 GitHub 里面建立 Projets，建立一个 Linkis0.11.0 的版本，并在里面加入详细功能版本先关内容
2. 建立 dev-0.11.0 的分支，进行 PR 提交，并 review 进行合并
3. 需要先提 Issue，并将讨论点反馈到 Issue 中

### 第二次开发交流（2020-05-09）

此次交流主要确定 Presto 引擎和 ES 引擎具体实现，调整了上次讨论的架构和一些细节的确定。相关问题讨论如下：

1. 采用 Entrance 的实现方式
采用 Entrance-em-engine 的模式，现在RM没法做到完整的资源控制，不能控制 ES 的并发，如果多个 Entrance 启动会导致用户的并发数做不到控制。

2. Entrance 端支持并发和单次查询的资源控制
Entrance 启动时注册资源（InstanceResource / PrestoResource），实现新的 EngineRequester 在创建 EntranceEngine 时向 ResourceManager 请求资源，执行完成后关闭 EntranceEngine 并释放资源。

3. 数据源模块结合
第一期数据源只支持一个在管理台进行配置，用户需要配置 URL 链接和 DataSourceName，第二期在单独的数据源模块服务支持

4. Entrance 环境隔离并兼容多环境
Gateway 中缓存环境和 Entrance 的映射并新增 ruler 进行转发，实现环境的隔离。在 Gateway 中维护映射时，需要考虑一致性。为了方便用户使用需要提供多环境的支持。

**Comment by wushengyeyouya** [comment]
感谢MobTech团队几位大神的倾情参与和贡献，为社区提供了呼声非常高的Presto引擎和ES引擎，是Linkis非常重要的一个版本，非常期待Linkis Release-0.9.5能尽快发布！

**Comment by jhj-123** [comment]
您好，这次的新版本，有没有解决高版本少jar包或者jar包冲突问题。

**Comment by cmdares** [comment]
期待新版本发布，希望能够整合更多类型的数据源，希望再补充进去一些常用数据源
1、Redis
2、Clickhouse
3、mongo

**Comment by wushengyeyouya** [comment]
> 期待新版本发布，希望能够整合更多类型的数据源，希望再补充进去一些常用数据源
> 1、Redis
> 2、Clickhouse
> 3、mongo

These engines will also be planned to Linkis Roadmap, if you are interested, welcome to join to develop and implement it

**Comment by wushengyeyouya** [comment]
> 您好，这次的新版本，有没有解决高版本少jar包或者jar包冲突问题。

Can you describe the problem in detail？

**Comment by iBuddha** [comment]
您好，新版的presto[已经支持LDAP](https://prestodb.io/docs/current/security/ldap.html)。我们在生产上也已经使用这种方式。希望Linkis新版本能支持使用用户名密码来查询Presto， 谢谢。

**Comment by wForget** [comment]
> 您好，新版的presto[已经支持LDAP](https://prestodb.io/docs/current/security/ldap.html)。我们在生产上也已经使用这种方式。希望Linkis新版本能支持使用用户名密码来查询Presto， 谢谢。

Presto引擎已经实现，有预留用户名密码，将于近期发布，可以拉取dev-0.11.0 分支使用。 https://github.com/WeBankFinTech/Linkis/tree/dev-0.11.0，

**Comment by wushengyeyouya** [comment]
This version has been released, now close the issue
