### ISSUE TITLE
[ContextService][Cache]To add support for CS cache function

### ISSUE THREAD

**Issue by peacewong** [WeBankFinTech/Linkis#368]
**Is your feature request related to a problem? Please describe.**
Accelerate the performance of accessing CS information, the response of DB query is too slow every time

**Describe the solution you'd like**
1. Support splitting by ContextType: speed up storage and query performance
2. Support splitting according to different ContextID: need to complete ContextID information isolation
3. Support LRU: recycle according to specific algorithm
4. Support indexing by keywords
5. Support indexing directly through ContextKey
6. Support traversal by ContextID, ContextType

**Comment by yangzhiyue** [comment]
thanks it is closed in #405
