### ISSUE TITLE
[ContextService][Search]To add support for CS search function

### ISSUE THREAD

**Issue by MountHuang** [WeBankFinTech/Linkis#372]
Is your feature request related to a problem? Please describe.
Enable searching from context cache objects by building conditions in a straightforward way. Complex conditions with multiple logic layers will be optimized to the most efficient sequence based on their cost information before acutally applied to context cache objects.

Describe the solution you'd like

1. Basic search conditions: Support accurate matching by context type, context scope and context value class type; Support fuzzy matching operations of contains, regular expressions and nearest selection.
2. Logical search conditions: Support flexible condition combination by And, Or, Not operations.
3. Condition Builder: Utility class makes building complex search conditions more convenient and easiear to understand.
4. Search optimization: Provide CBO based algorithm which reduces the total costs of complex search conditions.

**Comment by yangzhiyue** [comment]
thanks it is closed in #387
