### ISSUE TITLE
linkis能否解决这个自动登录的问题

### ISSUE THREAD

**Issue by JavaMrYang** [WeBankFinTech/Linkis#379]
linkis sdk执行报会话超时，用户未登录，之前是登录的可以执行，过了一段时间执行就提示用户未登录

**Comment by peacewong** [comment]
Hello, you can give the error log

**Comment by JavaMrYang** [comment]
公司在内网上，日志拿不出来。报的是getDirTrees no login之类的异常

**Comment by JavaMrYang** [comment]
fixed
