### ISSUE TITLE
Linkis1.1.0 community communication(Linkis1.1.0版本社区交流)

### ISSUE THREAD

**Issue by Adamyuanyuan** [WeBankFinTech/Linkis#382]
# Linkis0.11.0 community communication

Linkis0.11.0 version is an important version led by ctyun with the help of webank.
This release provides the following features to optimize engine startup speed:
- Support Spark dynamic resource allocation policy
- Introduce application manager (AM) to complete the transformation of engine preheating and recycling mechanism
- Archive engine archive information record
- Fix multiple known bugs to improve some error feedback experience
## First development communication (2020-04-30)
This communication mainly discussed the general plan and idea to optimize slow engine startup, related issues were discussed as follows:
1. Process startup time of engine can be optimized. For example, spark can use Driver resident, dynamic resource allocation strategy to shorten the time for users to obtain a usable engine.
2. Warm up the engine for users in advance. When a user submits a query, if no free engine is available, a new engine is requested to be started, then:
    a) if a user can control the number of a certain engine at a certain time, he can avoid starting the engine until he needs to submit tasks.
    b) more complicated condition, if we can automatically analyze the possible query submission time and the expected number of engines, then we can automatically start a sufficient number of engines for the user in advance.
3. Decide the conditions of engine recovery flexibly. The user's engine will be automatically recycled in the case of idle state for a long time, if we can predict that in a certain time, user may submit query again, we can choose to extend waiting time.
After the discussion, we decided that both teams can refine the slow engine optimization scheme respectively, and then meet again to determine the specific implementation scheme.
## Second development communication (2020-05-09)
In this communication, the ctyun team and the webank team fully exchanged opinions on the slow optimization of engine startup, and finally determined the specific implementation plan, adjusted the structure discussed last time and determined some details. The discussion conclusions of relevant issues are as follows:
1. Use Spark to dynamically allocate resource:
    a. Firstly, Spark dynamic resource allocation needs to be introduced into yarn;
    b. Add relevant configuration in the configuration module;
    c. Add relevant parameters when submitting the Spark job in the Spark-EnginManger module;
    d. In order to control resources more accurately, it is necessary to interact with ResourceManager at all stages of the engine life cycle to make resource-related requests and make corresponding modifications;
2. Engine preheating and recycling strategy optimization
    a. Add an Application Manager module, which is particulaly responsible for the scheduling management of the engine;
    b. The JobScanner periodically scans the preheating information configured by the user, screens out the jobs that need preheating, and starts a corresponding Task to preheat the engine;
    c. JobHistory monitors the state change of Job through JobScheduleListener and records the execution record history of Job;
    d. Use distributed locks in the process to ensure the consistency of the execution of specific tasks;
    e. Optimize the recycling strategy of the engine, let AM determines whether to recycle the engine or not;
    f. Reserve interfaces for further engine startup and recycling strategies based on complex algorithms;
3. Engine archive information record
    a. When the engine state changes, it will be reported through the interface of the RM;
    b. Write state flip information to HDFS file and archive;
    c. Record the execution of each task through JobHistory and add unique identification to provide a basis for further optimization;
4. Some other bug discussions and release methods

**Thanks to all the geniuses from webank for your help.** 

----

# Linkis0.9.6版本社区交流

Linkis0.11.0版本是在微众银行的倾力帮助下，由天翼云主导完成的一个重要版本。
该版本主要提供以下特性以优化引擎启动速度：
- 支持 Spark动态资源分配策略
- 引入应用管理器(AM)，完成引擎预热、回收机制的改造
- 引擎归档信息记录存档
- 修复多个已知bug，改善部分错误反馈体验

## 第一次开发交流（2020-04-30）

此次交流主要讨论了引擎启动慢优化的大致方案与思路，相关问题讨论如下：
1. 引擎进程启动时间本身具有优化空间。比如spark，可以采用Driver常驻、资源动态分配策略来缩短用户获取一个可用引擎的时间。
2. 提前为用户预热引擎。当用户提交查询时，如果没有可用的空闲引擎，就会请求启动一个新的引擎，那么：
a) 如果用户可以自主控制某种引擎在某个时间的数量，就能够避免提交任务时才去启动引擎。
b) 更复杂的是，如果可以自动分析用户可能提交查询的时间和预期引擎个数，就能够自动提前为用户启动足够数量的引擎。
3. 灵活判断引擎回收的条件。在长时间处于空闲状态的情况下，用户的引擎会被自动回收，如果可以预判在一定时间范围内，用户可能再次提交查询，则可以选择延长等待时间。

讨论后希望双方各自细化引擎慢优化方案，节后再碰一下确定具体实现方案。

## 第二次开发交流（2020-05-09）

这次交流天翼云团队与微众团队充分交换了关于引擎启动慢优化的意见，最终确定了具体实现方案，调整了上次讨论的架构和一些细节的确定。相关问题讨论结论如下：
1. 使用Spark动态资源分配：
    a. 首先需要在yarn中引入Spark动态资源分配；
    b. 在configuration模块中新增相关的配置；
    c. 在Spark-EnginManger模块中在提交spark作业时新增相关参数；
    d. 为更精确控制资源，需要在引擎生命周期各个阶段与ResourceManager交互，进行资源相关的请求，作相应的修改；
2. 引擎预热、回收策略改造
    a. 新增一个Application Manager模块，专门负责引擎的调度管理；
    b. 由JobScanner定时扫描用户配置的预热信息，筛选出需要预热的Job，启动一个对应的Task去预热引擎；
    c. JobHistory 通过 JobScheduleListener 监听Job的状态变化，记录Job的历史执行记录；
    d. 过程中做好分布式锁以保证具体Task执行的一致性；
    e. 优化引擎回收策略，由AM决定引擎是否回收；
    f. 为后续基于复杂算法的引擎启动与回收策略预留接口；
3. 引擎归档信息记录
    a. 引擎状态在进行变化时，通过RM将通过接口进行上报；
    b. 向HDFS文件写入状态翻转信息，并进行归档；
    c. 通过JobHistory记录每个任务每次执行的情况并加上唯一标识，为后续更加深入的优化提供基础；
4. 一些其它的bug讨论以及发布版本的方法

**感谢微众大神们的倾力协助**

**Comment by wushengyeyouya** [comment]
Thanks to the participation and contributions of several great gods of the Ctyun team, they have contributed engine startup optimization and complex engine recycle mechanisms to the community, which has greatly improved the response speed of Linkis' user computation jobs. At the same time, the ApplicationManager was first brought in this release. It is a deeply important release of Linkis, we look forward to the release of Linkis Release-0.9.6 as soon as possible!

---

感谢天翼云团队几位大神的倾情参与和贡献，为社区贡献了引擎启动慢优化和复杂的引擎回收机制，使Linkis的用户作业响应速度得到了极大的提升，同时首次引入了应用管理器(AM)，是Linkis非常重要的一个版本，非常期待Linkis Release-0.9.6能尽快发布！
