### ISSUE TITLE
[CS][UJES]UJES supports ContextService function

### ISSUE THREAD

**Issue by peacewong** [WeBankFinTech/Linkis#390]
**Is your feature request related to a problem? Please describe.**
Because of the realization of CS service, the function of interacting with CS needs to be added in the ujes part.

**Describe the solution you'd like**
The ujes part needs to add the function of interacting with CS.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by yangzhiyue** [comment]
thanks, it is closed in #429
