### ISSUE TITLE
[deploy]Modified public dependent lib is introduced through classPath

### ISSUE THREAD

**Issue by peacewong** [WeBankFinTech/Linkis#392]
**Is your feature request related to a problem? Please describe.**
The current common modules are copied to various services, which leads to troublesome operation and maintenance. Modifying a functional module will cause each service to be copied again.

**Describe the solution you'd like**
1. Modify the startup script of the service and add the classpath to specify the module directory
2. Modify the installation script, remove the copy part of the code

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by yangzhiyue** [comment]
thanks  it is fixed in #405
