### ISSUE TITLE
[Common]It is recommended to modify the queue of ListenerBus to ArrayBlockingQueue

### ISSUE THREAD

**Issue by peacewong** [WeBankFinTech/Linkis#395]
**Is your feature request related to a problem? Please describe.**
ArrayBlockingQueue has better performance and compatibility

**Describe the solution you'd like**
 to modify the queue of ListenerBus to ArrayBlockingQueue.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by yangzhiyue** [comment]
thanks  it is fixed, and we will use ArrayBlockingQueue as default
