### ISSUE TITLE
[deploy] Linkis on k8s (Linkis 0.10.0)

### ISSUE THREAD

**Issue by brianzhangrong** [WeBankFinTech/Linkis#396]
Linkis 0.10.0 is an important version led by Ihome.

This version mainly provides the following features：

Linkis on  k8s
Fix multiple bugs
The first development communication (2020-05-25)
This communication mainly discusses the general implementation ideas of Linkis on k8s. Related issues are discussed as follows:

Why k8s?
without artifactory CD we meet some problem，sit/UAT/STAGE  envirment  we need test every time.  

Ihome Works
Dockerfile development.
k8s yaml development.

WeBank Works
Assist Ihome related personnel to complete the development work.
Support Nacos  service discovery .
Release context function of linkis and DSS, and fix PR of multiple bugs.
About how to release the version
It will create projects in GitHub, build a version of linkis 0.10.0, and add dockerfile,k8s yaml first

Establish a branch of dev-0.10.0, submit PR, and review for consolidation
Issue needs to be mentioned first, and the discussion points need to be fed back to issue
The second development communication (2020-05-28)
This communication mainly determines the specific implementation of Linkis on k8s and adjusts the architecture discussed last time and the determination of some details. Related issues are discussed as follows:

Suport Nacos to discovery micro-service and config server.

Linkis0.10.0版本社区交流
Linkis0.10.0版本是由 Ihome 主导完成的一个重要版本。

该版本主要提供以下特性：

支持 Linkis on k8s
修复多个bug
第一次开发交流（2020-05-25）
此次交流主要讨论云原生给linkis生态带来哪些利器。相关问题讨论如下：

弹性扩容，支持一件扩缩容任意数量微服务，在资源允许的条件下
即开即用，减少运维工作量，docker作为制品发布，能够有效避免每家公司都调试一遍微服务及环境（SIT，UAT，STAGE）问题
资源隔离，基于cgroup，namespace及统一文件系统之上的部署架构，能够隔离微服务不超卖cpu，mem，net，disk

Ihome工作
完成dockerfile 开发
完成 k8s yaml 开发
联调linkis on k8s
提供公有云 linkis on k8s，提供jenkins on k8s 做为dev_0.10.0持续交付集成
微众工作
协助 Ihome 相关人员完成开发工作
Nacos 服务发现扩展性支持

关于怎么发布版本
会在 GitHub 里面建立 Projets，建立一个 Linkis0.10.0 的版本，并在里面加入详细功能版本先关内容
建立 dev-0.10.0 的分支，进行 PR 提交，并 review 进行合并
需要先提 Issue，并将讨论点反馈到 Issue 中
第二次开发交流（2020-05-28）
此次交流主要确定API市场相关功能（One Service）：

数据源模块结合
jdbc数据源支持别名引用
向导式发布rest 服务
API应用市场可以查看API及申请使用

**Comment by wushengyeyouya** [comment]
Linkis on k8s (Linkis 0.10.0)  will be published in this or the next week, please stay tuned!

**Comment by Vinsmoke66** [comment]
When will this version be released?

**Comment by wushengyeyouya** [comment]
Thanks for the contribution of Ihome, this version is released, now close this issue.
