### ISSUE TITLE
[JobHistory][Entrance]Task cannot be killed because there is no execID record in the entrance

### ISSUE THREAD

**Issue by peacewong** [WeBankFinTech/Linkis#398]
**Describe the bug**
Now, when Entrance restarts unexpectedly, it will cause the previously running tasks to not be killed.

**To Reproduce**
1. run .sql task
2. restart SparkEntrance
3. Kill task will report execID notFound exception

**Comment by yangzhiyue** [comment]
thanks it is close in #398
