### ISSUE TITLE
linkis connect hive error org.datanucleus.exceptions.NucleusException: Error creating transactional connection factory

### ISSUE THREAD

**Issue by ly-yhq** [WeBankFinTech/Linkis#4552]
### Before asking

- [X] I have read the [How to ask for help](https://linkis.apache.org/community/how-to-ask-for-help) (我已阅读[如何寻求帮助](https://linkis.apache.org/zh-CN/community/how-to-ask-for-help)指引文档).

### Your environment

- Linkis version used: 1.3.2
- Environment name and version:
    - hadoop-2.7.2
    - hive-2.1.1
    - spark-2.4.3
    - scala-2.13.0
    - jdk 1.8.0_351

### Describe your questions

Q1.  linkis连接hive报错，org.datanucleus.exceptions.NucleusException: Error creating transactional connection factory

![image](https://github.com/apache/linkis/assets/44761036/f1b56a8a-f4b3-4e4e-a632-fd1abbfa94b2)

### Eureka service list

![Snipaste_2023-05-17_20-30-02](https://github.com/apache/linkis/assets/44761036/51ca42ea-2d1b-4bd2-b1e9-2c9817911f50)

### Some logs info or acctch file

linkis-xxx.log:
````log

<!--日志文字贴到这里-->
2023-05-17 20:06:58.006 ERROR jobRequest(IDE_root_hive_2)  execute failed,21304, Task is Failed,errorMsg: FAILED: SemanticException org.apache.hadoop.hive.ql.metadata.HiveException: java.lang.RuntimeException: Unable to instantiate org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient 
````
log file:
 

[error.txt](https://github.com/apache/linkis/files/11498115/error.txt)

**Comment by peacewong** [comment]
It is necessary to put datanucleus related packages into the lib of hive ec(需要将datanucleus相关的包放到hive ec的lib中)

**Comment by ly-yhq** [comment]
> 有必要将 datanucleus 相关包放入 hive ec 的 lib 中（需要将 datanucleus 相关的包放到hive ec的lib中）


I have already placed these packages in hive's lib, may I know which ones are still missing
![image](https://github.com/apache/linkis/assets/44761036/3e6501a7-4a62-4424-ba43-0e6b545cbe54)
