### ISSUE TITLE
start-all.sh脚本日志打印不够详细

### ISSUE THREAD

**Issue by xinda77** [WeBankFinTech/Linkis#46]
1，我是在CDH平台的，编译后安装完成，启动脚本执行日志打印如下
We will start all linkis applications, it will take some time, please wait
<-------------------------------->
Begin to start Eureka Server
INFO: + End to start Eureka Server
<-------------------------------->
<-------------------------------->
Begin to start Gateway
INFO: + End to start Gateway
<-------------------------------->
<-------------------------------->
Begin to start Public Service
INFO: + End to start Public Service
<-------------------------------->
<-------------------------------->
Begin to start metadata
INFO: + End to start Metadata
<-------------------------------->
<-------------------------------->
Begin to start Resource Manager
INFO: + End to start Resource Manager
<-------------------------------->
sleep 15 seconds to wait RM to be ready
<-------------------------------->
Begin to start Spark Entrance
End to end Spark Entrance started
<-------------------------------->
<-------------------------------->
Begin to Spark Engine Manager
End to start Spark Engine Manager 
<-------------------------------->
<-------------------------------->
Begin to start Hive Entrance
End to start Hive Entrance
<-------------------------------->
<-------------------------------->
Begin to start Hive Engine Manager
End to start Hive Engine Manager
<-------------------------------->
<-------------------------------->
Begin to start Python Entrance
End to start Python Entrance
<-------------------------------->
<-------------------------------->
Begin to start Python Engine Manager
End to start Python Engine Manager
<-------------------------------->
start-all shell script executed completely
但是服务没有启动，也不知道什么错，在安装目录单启动服务正常启动

**Comment by wushengyeyouya** [comment]
We will fix it in Linkis release0.9.0, you can try to manually start each service first.

**Comment by peacewong** [comment]
This issue has been fixed
