### ISSUE TITLE
0.8.0版本 stop-all.sh脚本无法stop掉进程linkis-metadata

### ISSUE THREAD

**Issue by Just-do-it-Fan** [WeBankFinTech/Linkis#48]
**Describe the bug**
0.8.0版本 stop-all.sh脚本无法stop掉进程linkis-metadata

**To Reproduce**
1. ./bin/start-all.sh
2. ./bin/stop-all.sh

**Expected behavior**
停掉所有相关进程，但linkis-metadata进程没有停掉

**Screenshots**
![image](https://user-images.githubusercontent.com/22441484/64778056-e1635800-d58d-11e9-9866-4c59cc88bdfe.png)

**Additional context**
发现stop-all.sh脚本中变量名DATABASE_NAME的值与start-all.sh中该变量名的值不一致，导致无法正确stop掉相应进程

**Comment by wushengyeyouya** [comment]
Thanks, We will fix it at Linkis release0.9.0
