### ISSUE TITLE
使用HDP集群时，查看队列管理器报错

### ISSUE THREAD

**Issue by Vinsmoke66** [WeBankFinTech/Linkis#486]
**Describe the bug**
error code(错误码)：11006, error message(错误信息): Get the Yarn queue information exception.(获取Yarn队列信息异常).

![image](https://user-images.githubusercontent.com/21305459/89769521-d4e5d780-db2f-11ea-89ba-261d13e5e80b.png)

linkis-resourcemanager报错：
![image](https://user-images.githubusercontent.com/21305459/89769757-4c1b6b80-db30-11ea-992c-1ae4277a091e.png)

Caused by: java.lang.ClassCastException: org.json4s.JsonAST$JDouble cannot be cast to org.json4s,JsonAST$JDecimal

解决办法：
YarnUtils里第136行的报错那里，有两个JDecimal，需要改成JDouble，重新打包上传替换，重启linkis-resourcemanager

**Comment by peacewong** [comment]
已经修改好的包，链接：https://pan.baidu.com/s/1j2PKX1h5jKCVZ_Ak5Xylzg 
提取码：b8s3

**Comment by bobzhangfw** [comment]
有效果。解决困扰一周的问题了。
