### ISSUE TITLE
[Bug][SSO] The problem of user cookie loss after single sign-on access

### ISSUE THREAD

**Issue by linweijiang** [WeBankFinTech/Linkis#489]
After SSO, web returns to the homepage, if you continue to click on other pages, the authentication failure will occur. After checking the page request details, it is found that there is no bdp-user-ticket-id cookie

单点登录成功返回首页后，继续点其他页面会出现认证失败问题，查看页面请求详情后发现没有 bdp-user-ticket-id cookie

**Comment by wushengyeyouya** [comment]
Thanks very much!
