### ISSUE TITLE
python engine has some problems

### ISSUE THREAD

**Issue by Vinsmoke66** [WeBankFinTech/Linkis#507]
![image](https://user-images.githubusercontent.com/21305459/98901637-156a3e00-24ef-11eb-9200-9e7ce466d0da.png)
When I use python scrapy to crawling web pages, it could not finish the job and always in queue. 
I try to find the error information in the log, but I couldn't find it.

The code is:
`import scrapy
from scrapy.crawler import CrawlerProcess
from scrapy.linkextractors import LinkExtractor
from scrapy.spiders import CrawlSpider, Rule
from scrapy import Selector

class MyspiderSpider(CrawlSpider):
    name = 'myspider'
    allowed_domains = ['ip']
    start_urls = ['http://xxx.html']
    rules = (
        Rule(LinkExtractor(restrict_xpaths='//ul[@class="unstyled1"]//a'), callback='parse_item', follow=True),
    )
    def parse_item(self, response):
        datas = response.xpath('//tbody//tr').getall()
        filename = '/tem/xxx.txt'
        for data in datas:
            data=Selector(text=data).xpath(".//td//text()").getall()
            for d in data;
            	print(d)

process = CrawlerProcess(settings={
    "FEEDS": {
        "items.json": {"format": "json"},
    },
})

process.crawl(MyspiderSpider)
process.start() `

**Comment by peacewong** [comment]
Hello, are there multiple python jobs running at the same time?

**Comment by Vinsmoke66** [comment]
> Hello, are there multiple python jobs running at the same time?

no, only one job.

**Comment by peacewong** [comment]
> > Hello, are there multiple python jobs running at the same time?
> 
> no, only one job.

You can see if Python entrance has accepted this job. If the job is in the queue, there are several reasons:
1. The number of jobs exceeds the limited default three
2. The entrance did not receive the Job
