### ISSUE TITLE
There is no way to run my code with custom dependencies

### ISSUE THREAD

**Issue by yonger1516** [WeBankFinTech/Linkis#511]
**Describe the bug**
For Spark engine，only driver classpath appending is supportted, there is no way to add any dependency jars into classpath for executors.

  ```
  this.driverClassPath(SPARK_CONF_DIR.getValue)
    this.driverClassPath(HADOOP_CONF_DIR.getValue)
    this.driverClassPath(SPARK_DRIVER_CLASSPATH.getValue)
``` 

**Expected behavior**
if there is any workaround before bug fixing, pls show me the guide instead of a word.

**Comment by peacewong** [comment]
Hello, this is supported, you can configure the --jars parameter, you can refer to SparkSubmitProcessBuilder class
```
SparkSubmitProcessBuilder:
properties.getOrDefault("jars", "").split(",").map(RelativePath).foreach(jar)

```
