### ISSUE TITLE
创建项目，如果dss-schedulis 不通会创建失败，再次创建会提示已存在。

### ISSUE THREAD

**Issue by hcl3039359** [WeBankFinTech/Linkis#515]
创建项目，如果dss-schedulis 不通会创建失败，再次创建会提示已存在。

**Comment by DADA-shuai** [comment]
创建之后应该会把数据保存到数据库里，把数据库的记录删一下应该就能再次创建了

**Comment by hcl3039359** [comment]
> 创建之后应该会把数据保存到数据库里，把数据库的记录删一下应该就能再次创建了

最好还是保持事务性吧

**Comment by peacewong** [comment]
Hello, this bug will be fixed in the dss project, we will close this issue
