### ISSUE TITLE
脚本获取结果集失败

### ISSUE THREAD

**Issue by zhanghaicheng1** [WeBankFinTech/Linkis#547]
![image](https://user-images.githubusercontent.com/46189785/103722019-05ac3900-500a-11eb-819e-ec8077ab7c26.png)
查询hql/sql，获取结果集失败，时好时坏，有的时候能查询出来，有的时候查询不出来，后台日志也没有错误。

**Comment by peacewong** [comment]
Hello, you can check the log of linkis-publicservice

**Comment by zhanghaicheng1** [comment]
相同的请求，有的时候请求可以，有的时候请求不行！
![image](https://user-images.githubusercontent.com/46189785/103726245-655b1200-5013-11eb-820e-0f94bc9069c8.png)
![image](https://user-images.githubusercontent.com/46189785/103726287-815eb380-5013-11eb-94f6-5ad089495a36.png)
linkis-publicservice没有错误信息
![image](https://user-images.githubusercontent.com/46189785/103726341-af43f800-5013-11eb-8591-d3b0438f2c4e.png)

**Comment by zhanghaicheng1** [comment]
解决思路：（已解决）
1、nginx配置缓冲区大小：client_max_body_size
2、查看nginx工作进程的运行用户：#ps aux | grep "nginx: worker process" | awk '{print $1}'，假设结果是nobody
3、根据第二步得到的结果对proxy_temp进行赋权：chown -R nobody:nobody proxy_temp
