### ISSUE TITLE
Invalid bound statement (not found): com.webank.wedatasphere.linkis.metadata.hive.dao.HiveMetaDao.getDbsByUser

### ISSUE THREAD

**Issue by sewenc** [WeBankFinTech/Linkis#550]
**列出hive数据库时报错**
Invalid bound statement (not found): com.webank.wedatasphere.linkis.metadata.hive.dao.HiveMetaDao.getDbsByUser

页面位置如下图：
![image](https://user-images.githubusercontent.com/40030020/104141952-3ae2cd80-53f4-11eb-9924-c86363310be1.png)

报错模块：
![image](https://user-images.githubusercontent.com/40030020/104141987-66fe4e80-53f4-11eb-981c-2840648d4a82.png)

自编译,版本为：linkis:0.10.0, hadoop:2.8.3,hive:2.1.1

**Comment by bertramlau** [comment]
可以检查一下linkis-metadata是否有访问hive meta数据库的权限

**Comment by sewenc** [comment]
看到日志以后解决了此问题，谢谢

**Comment by DADA-shuai** [comment]
具体是什么问题呢，之前我能访问，但是现在也访问不了了，报的错和你一样
