### ISSUE TITLE
"open file" issue at workspace when upgrading Linkis from 093 to 0100

### ISSUE THREAD

**Issue by yonger1516** [WeBankFinTech/Linkis#551]
![image](https://user-images.githubusercontent.com/6733760/104400844-073bab00-558e-11eb-98ea-7e4164d7fcd9.png)

**Comment by yonger1516** [comment]
and the comparison screenshot from linkis 093:
![image](https://user-images.githubusercontent.com/6733760/104400942-33572c00-558e-11eb-92ca-549df5714ea0.png)

**Comment by peacewong** [comment]
Hello, the interface for opening files is standardized after version 0.9.4, and you need to upgrade the dss
