### ISSUE TITLE
Cannot connect through JDBC with README.md

### ISSUE THREAD

**Issue by syobject** [WeBankFinTech/Linkis#559]
**Describe the bug**
There are no JDBC connections in the Maven library

**To Reproduce**
1. Go to  https://github.com/WeBankFinTech/Linkis/wiki/%E9%80%9A%E8%BF%87JDBC%E8%BF%9E%E6%8E%A5Linkis
2. The first step is to introduce the dependency module
    <dependency>
            <groupId>com.webank.wedatasphere.linkis</groupId>
            <artifactId>linkis-ujes-jdbc</artifactId>
            <version>0.9.1</version>
        </dependency>
3. See error .can not find linkis-ujes-jdbc in Maven repository

**Expected behavior**
1. Update the wiki documentation, focusing on connecting to the usage documents（）
2. Update the Maven repository or show how to connect it correcttly。

**Screenshots**
![image](https://user-images.githubusercontent.com/41422213/106726651-98f67f80-6645-11eb-9de8-4db449cb271e.png)
can not find linkis-ujes-jdbc in Maven repository

**Desktop (please complete the following information):**
 - win10
 - no Browser 
 - linkis master branch
 - use idea （The latest）

**Comment by peacewong** [comment]
Thank you, the linkis-jdbc-driver module has not been deployed to Maven. We will modify the documentation and deploy it to Maven in the next version.
![image](https://user-images.githubusercontent.com/11496700/108450053-78fac900-729f-11eb-8296-cb53a1ab192d.png)

**Comment by syobject** [comment]
Thank you for your reply. The problem has been solved in a timely manner


| |
石勇
|
|
syobject@163.com
|
签名由网易邮箱大师定制
On 2/19/2021 10:45，johnnywang<notifications@github.com> wrote：

Thank you, the linkis-jdbc-driver module has not been deployed to Maven. We will modify the documentation and deploy it to Maven in the next version.
