### ISSUE TITLE
 [Update] After Linkis-0.9.4 enables LDAP and proxy user mode, DSS is still used to log in users to perform tasks

### ISSUE THREAD

**Issue by Tandoy** [WeBankFinTech/Linkis#562]

**Comment by Tandoy** [comment]
1.linkis-gateway/proxy.properties
liurijia=appuser
2.
![捕获](https://user-images.githubusercontent.com/56899730/106853300-73747f00-66f4-11eb-9d8b-278f4693263e.PNG)

**Comment by peacewong** [comment]
Hello, have you set this parameter? `wds.linkis.gateway.conf.enable.proxy.user=true`

**Comment by Tandoy** [comment]
> Hello, have you set this parameter? `wds.linkis.gateway.conf.enable.proxy.user=true`

linkis-gateway/conf/linkis.properties，This configuration file, I have already done; amount of related settings。
![捕获](https://user-images.githubusercontent.com/56899730/108447461-ddfff000-729a-11eb-9c39-4816863df34d.PNG)

**Comment by peacewong** [comment]
Can you find these two lines in the Gateway log.
![image](https://user-images.githubusercontent.com/11496700/108449146-f32a4e00-729d-11eb-82d6-210d446c975d.png)

**Comment by Tandoy** [comment]
> Can you find these two lines in the Gateway log.
> ![image](https://user-images.githubusercontent.com/11496700/108449146-f32a4e00-729d-11eb-82d6-210d446c975d.png)

When I run a job, I cannot find those two log lines in the Gateway log.

**Comment by Tandoy** [comment]
Debug shows ENABLE_PROXY_USER.getValue=true, but scheduleAtFixedRate() will not be executed. Why?
![Snipaste_2021-03-01_18-09-17](https://user-images.githubusercontent.com/56899730/109485406-9fe5a600-7abc-11eb-85f2-04f15fba33ce.png)

**Comment by peacewong** [comment]
Hello, you can try catch this run method to see if there is any exception information
