### ISSUE TITLE
数据库获取失败，一直刷新状态

### ISSUE THREAD

**Issue by zhanghaicheng1** [WeBankFinTech/Linkis#690]
求教！！！
后台日志如下图：
![image](https://user-images.githubusercontent.com/46189785/111949614-fd00d480-8b1b-11eb-9b0f-07c96a5301c0.png)
前端：
![image](https://user-images.githubusercontent.com/46189785/111949660-10ac3b00-8b1c-11eb-9de1-dcffe50e693b.png)

**Comment by emerkfu** [comment]
解决方法：

修改linkis-metadata配置文件如下图
![image](https://user-images.githubusercontent.com/59500675/111978243-ae186680-8b3e-11eb-958b-00d9bbcb48ac.png)

配置元数据库配置，重启linkis-metadata后该问题大概率可以解决。

**Comment by zhanghaicheng1** [comment]
1.0RC1版本，这个配置已经配置了呢。还是无法加载数据库

**Comment by Tandoy** [comment]
https://github.com/WeBankFinTech/Linkis/wiki/Q&A-%E9%97%AE%E9%A2%98%E6%80%BB%E7%BB%93，可参考第六点尝试修改。

**Comment by Tandoy** [comment]
https://github.com/WeBankFinTech/Linkis/wiki/Q&A-%E9%97%AE%E9%A2%98%E6%80%BB%E7%BB%93
可参考第六点尝试修改。
