### ISSUE TITLE
工作流中数据开发组件关联脚本选项，选择脚本后提示关联脚本失败 NullPointerException

### ISSUE THREAD

**Issue by zoneyeah** [WeBankFinTech/Linkis#691]
**Describe the bug**
工作流中数据开发组件关联脚本选项，选择脚本后提示关联脚本失败 NullPointerException
![图片](https://user-images.githubusercontent.com/81277410/112250544-863b1700-8c94-11eb-9935-00429c18998f.png)

../dss_linkis/linkis/linkis-publicservice/logs/linkis.log   有如下异常提示
![图片](https://user-images.githubusercontent.com/81277410/112250769-f6499d00-8c94-11eb-8501-15f243f419a2.png)

linkis版本0.11.0  dss版本0.9.0

**Comment by lordk911** [comment]
同样的问题，DSS0.9.1 \ linkis0.9.4

**Comment by peacewong** [comment]
Hello, this problem has been solved in DSS [DSS-230](https://github.com/WeBankFinTech/DataSphereStudio/pull/230)
