### ISSUE TITLE
精简版本python entrance启动报错,hdfs configuration was not read

### ISSUE THREAD

**Issue by wyx94** [WeBankFinTech/Linkis#70]
精简版本python entrance启动初始化，初始化ErrorCodeManager时
默认解析errorCodeFileDir为hdfs类型文件，需要环境设置hadoop_conf_dir

**Comment by wForget** [comment]
请问这个问题怎么解决的？我在虚拟机装的还没有hadoop环境

**Comment by cwr31** [comment]
> 请问这个问题怎么解决的？我在虚拟机装的还没有hadoop环境

必须要hadoop环境的

**Comment by muicoder** [comment]
终端下执行：`export HADOOP_CONF_DIR=/appcom/config/hadoop-config/`，目录是必须存在的
