### ISSUE TITLE
use dss create table or database,Unable to get new table from api

### ISSUE THREAD

**Issue by sewenc** [WeBankFinTech/Linkis#702]
**Describe the bug**
use dss create table,Unable to get new table from api

**To Reproduce**
1. open dss
2. exec hive sql: create database dwd;
3. Refresh database list ,
4. No database dwd in list

linkis version: 0.9.0
 
**Additional context**
![image](https://user-images.githubusercontent.com/40030020/113737826-f637ab80-9730-11eb-9612-2b42553a2c15.png)

i find sql,find not data in TBL_PRIVS:
```sql
select t3.NAME as NAME
from TBL_PRIVS t1, TBLS t2 , DBS t3
where t1.TBL_ID=t2.TBL_ID and lcase(t1.TBL_PRIV) in ('select','all') and (
            lcase(t1.PRINCIPAL_NAME) = 'root' or lcase(t1.PRINCIPAL_NAME) in (SELECT ROLE FROM(SELECT r.ROLE_NAME AS ROLE, u.PRINCIPAL_NAME AS USER FROM ROLES r LEFT JOIN (SELECT * FROM ROLE_MAP WHERE PRINCIPAL_TYPE = 'USER') u ON r.ROLE_ID = u.ROLE_ID)AS T where T.USER = 'root'))
  and t2.DB_ID=t3.DB_ID
```

**Comment by sewenc** [comment]
## 原因
linkis默认开启 hive的权限,而真实情况是hive没有开,导致通过有权限的sql查不出结果

## 解决办法
修改linkis的查询表与数据库的权限sql:
修改文件: HiveMetaDao.xml

将这两个sql改成这样(原始的非常复杂):
```sql
    <select id="getDbsByUser" resultType="java.lang.String" parameterType="java.lang.String" databaseId="mysql">
        SELECT NAME FROM DBS;
    </select>

    <select id="getTablesByDbNameAndUser" resultType="map"  parameterType="map" databaseId="mysql">
        select t2.TBL_NAME as NAME, t2.TBL_TYPE as TYPE, t2.CREATE_TIME as CREATE_TIME, t2.LAST_ACCESS_TIME as LAST_ACCESS_TIME, t2.OWNER as OWNER
        from TBLS t2, DBS t3
        where  t2.DB_ID=t3.DB_ID and t3.NAME = #{dbName,jdbcType=VARCHAR}
    </select>
```

**Comment by leeebai** [comment]
Thank you for providing solutions for removing Hive authentication issues.
I will help you replace the title, let other developers who have the same needs as you can quickly retrieve this Issue.
