### ISSUE TITLE
开源范围咨询,带开源是部署问题还是什么问题呢

### ISSUE THREAD

**Issue by qjws** [WeBankFinTech/Linkis#708]
0.9.1
![1619656728(1)](https://user-images.githubusercontent.com/33768151/116489208-f86fce80-a8c6-11eb-9815-ac3d301a7839.jpg)
![1619656837(1)](https://user-images.githubusercontent.com/33768151/116489213-fb6abf00-a8c6-11eb-85bc-2931abaea501.jpg)

**Comment by qjws** [comment]
部署的是 0.9.1 标准版本
请问,我想看 标准版本全部功能  应该 部署什么版本以上呢? 还是 现在开源进度确实不支持?

**Comment by peacewong** [comment]
Hello, you can refer to this PR to solve this problem, because the initialization data is missing：https://github.com/WeBankFinTech/DataSphereStudio/pull/226

**Comment by lichuang22** [comment]
> 部署的是0.9.1标准版本
> 请问，我想看标准版本全部功能应该部署什么版本以上呢？还是现在开源进度确实不支持？

请问这个问题怎么解决的啊，我也遇到了
