### ISSUE TITLE
mvn 编译错误

### ISSUE THREAD

**Issue by myetl** [WeBankFinTech/Linkis#78]
etadata/src/main/assembly/distribution.xml
resourceManager/resourcemanagerserver/src/main/assembly/distribution.xml

这两个文件中 去掉  
   <exclude>xml-apis:xml-apis:jar</exclude> 
才能编译通过 否则报错

**Comment by peacewong** [comment]
Hello, this issue has been fixed, you can use the latest 0.9.3 version
