### ISSUE TITLE
[编译失败] 子模块pom文件都需要添加relativePath

### ISSUE THREAD

**Issue by wangshu-zhouyunfan** [WeBankFinTech/Linkis#79]
**Describe the bug**
目前子模块pom文件没有设定relativePath，使得mvn在编译的时候从本地仓库以及远程仓库去获取父项目依赖的包。但是由于Linkis并没有公共的仓库，会导致用户编译过程中会失败。

**To Reproduce**
1. 把各个子项目的主pom.xml parentp配置添加relativePath字段，并配置正确路径。

**Comment by peacewong** [comment]
Hello, you can use mvn clean install to compile
