### ISSUE TITLE
Does Linkis 1.0.0-RC1 support DSS 0.9.1?

### ISSUE THREAD

**Issue by jarvisqi** [WeBankFinTech/Linkis#826]
Can I upgrade Linkis 1.0.0-RC1 directly with DSS 0.9.1?Do you support it?
Or when do you plan to support it?
请问目前使用dss 0.9.1 ，可以直接升级 Linkis 1.0.0-RC1 吗？  是否支持？
或者有计划打算什么时候支持？

**Comment by duanbt** [comment]
同问

**Comment by jacktao007** [comment]
Incompatible, wait for DSS1.0 release
