### ISSUE TITLE
Rename the package after front end build

### ISSUE THREAD

**Issue by demonray** [WeBankFinTech/Linkis#832]
**Describe the bug**
The fronted build packages should be named  `wedatasphere-links-**`  ？

**To Reproduce**
1. cd web
2. npm install
3. npm run build

**Expected behavior**

**Additional context**
replace ‘dss' in file `web/config.sh`,`web/install.sh`

**Comment by lindychan** [comment]
I will fix it ,right away.

**Comment by det101** [comment]
It should also include  vue.config *-DataSphereStudio-*-dist.zip
I will fix it
