### ISSUE TITLE
ldpa用户无法登陆dss

### ISSUE THREAD

**Issue by snow-sunshine** [WeBankFinTech/Linkis#833]
ldpa用户无法登陆dss
javax.naming.InvalidNameException: [LDAP: error code 34 - invalid DN]
ldap语法错误 debug后 linkis-common 的LDAPUtils获取SECURITY_PRINCTPAL错误

ldap_security_principal,  用来查询验证ldap服务的用户，如 cn=uname,ou=People,dc=zhangy,dc=com，或者有可能是uid=uname,ou=People,dc=zhangy,dc=com
![image](https://user-images.githubusercontent.com/52727477/124093123-22419f00-da8a-11eb-8b2f-a9eec81a8d55.png)
根据个人情况修改代码
env.put(Context.SECURITY_PRINCIPAL, bindDN)    --->
env.put(Context.SECURITY_PRINCIPAL, "uid="+bindDN+",ou=People,"+baseDN)

**Comment by wForget** [comment]
can add `wds.linkis.ldap.proxy.userNameFormat` configuration like "cn=%s,ou=People,dc=zhangy,dc=com"
