### ISSUE TITLE
Failed to generate hive.meta when hive meta URL contains special characters

### ISSUE THREAD

**Issue by wuhuaidong** [WeBankFinTech/Linkis#834]
When installing hive in the linkis-env.sh file under the package config_ META_ When the URL contains special characters
As follows: hive_ META_ URL=jdbc: mysql://XXX:3306/metastore?
当安装包config下面的linkis-env.sh文件中的HIVE_META_URL包含特殊字符时
如下：HIVE_META_URL=jdbc:mysql://XXX:3306/metastore?useSSL=false&createDatabaseIfNotExist=true&characterEncoding=UTF-8

The hive.meta.url generated to the links PS publicservice.properties file will be empty
生成到linkis-ps-publicservice.properties文件中的hive.meta.url 会为空

**Comment by fancyChuan** [comment]
我来尝试修复这个issue

**Comment by fancyChuan** [comment]
The & symbol has a special meaning in the shell. When assigning HIVE_META_URL directly in linkis-env.sh, you need to add double quotes to turn the URL into a normal string。

&符号在shell中具有特殊的含义，直接在linkis-env.sh中给HIVE_META_URL赋值的时候，需要加上双引号将url变为普通字符串
