### ISSUE TITLE
Compilation of linkis oom failed

### ISSUE THREAD

**Issue by CCweixiao** [WeBankFinTech/Linkis#838]
After modifying the Hadoop version, compiling linkis-1.0 failed, memory overflow or GC problems, and adjusting Maven parameters are not good. Maven version is 3.6.3, which fails to compile on 16g Mac and 32g centos7
修改Hadoop版本后，编译linkis-1.0失败，内存溢出或GC问题，调整maven参数也不行，maven 版本是3.6.3，16G mac和32G centos7上编译都无法通过

export MAVEN_OPTS='-Xmx10240m -XX:MetaspaceSize=2048m -XX:MaxMetaspaceSize=2048m'

<img width="903" alt="wecom-temp-9e67754588ac0f72156ca99403a5e096" src="https://user-images.githubusercontent.com/27730211/124479345-c0aa6900-ddd8-11eb-88a5-b8772817a6ab.png">

**Comment by leeebai** [comment]
看起来所有的子模块都打包成功了，只是合并打包的assembly内存溢出，可以尝试单独在wedatasphere-linkis-combined-package目录下打包该模块，如果还不成功，可以尝试非合并打包方式的assembly

**Comment by CCweixiao** [comment]
> 看起来所有的子模块都打包成功了，只是合并打包的assembly内存溢出，可以尝试单独在wedatasphere-linkis-combined-package目录下打包该模块，如果还不成功，可以尝试非合并打包方式的assembly

非常感谢回复，正在尝试中国呢

**Comment by leeebai** [comment]
非合并打包的方式是在linkis/assembly下打包，功能是一样的，微服务数量会比合并打包的方式多几个

**Comment by CCweixiao** [comment]
> 在linkis/assembly

![image](https://user-images.githubusercontent.com/27730211/124539583-56cda600-de50-11eb-9a60-bd401ca720ca.png)
这个目录下嘛？具体咋操作，可不可以帮忙更新下编译文档，非常感谢 非常感谢

**Comment by leeebai** [comment]
linkis1.0正式版移除的非合并的打包方式，有没有可能是机器本身的可用内存不足，这个也会导致内存溢出问题

**Comment by CCweixiao** [comment]
> linkis1.0正式版移除的非合并的打包方式，有没有可能是机器本身的可用内存不足，这个也会导致内存溢出问题
![企业微信截图_ed6a03e9-2196-4fd2-bd5f-b813dc0d346a](https://user-images.githubusercontent.com/27730211/124695859-9a8ae300-df16-11eb-906a-4000538bd795.png)
可用内存我看还行，你们的编译是在服务器上进行的嘛？是否有这个问题，你们的maven参数设置的怎样，可以给一个参考嘛。

**Comment by CCweixiao** [comment]
我现在根据assembly 中的描述文件，把各个模块下target目录打好的脚本，写脚本copy 到一个目录下，然后替换安装包的lib目录中的内容，这种方案是否需要注意些什么？

**Comment by leeebai** [comment]
我们是在windows上面打包的，没有特殊的参数设置，我自己使用的maven版本是3.6.1，目前来看8G的可用内存是完全够的

**Comment by leeebai** [comment]
> 我现在根据assembly 中的描述文件，把各个模块下target目录打好的脚本，写脚本copy 到一个目录下，然后替换安装包的lib目录中的内容，这种方案是否需要注意些什么？

如果是自己copy，需要特别注意assembly-combined打包内容的文件夹名和路径，如果有出入大概率会有问题

**Comment by CCweixiao** [comment]
> 我们是在windows上面打包的，没有特殊的参数设置，我自己使用的maven版本是3.6.1，目前来看8G的可用内存是完全够的。

打包命令mvn clean install 应该是这样 没错吧

**Comment by leeebai** [comment]
> > 我们是在windows上面打包的，没有特殊的参数设置，我自己使用的maven版本是3.6.1，目前来看8G的可用内存是完全够的。
> 
> 打包命令mvn clean install 应该是这样 没错吧

是的
