### ISSUE TITLE
hive engine don't support the data including \t,because the default return data split by \t

### ISSUE THREAD

**Issue by xiaojie19852006** [WeBankFinTech/Linkis#855]
hive engine don't support the data including \t,because the default return data split by \t

the code：
scalaResult foreach { s =>
                      val arr: Array[String] = s.split("\t")
                      val arrAny: ArrayBuffer[Any] = new ArrayBuffer[Any]()
                      if (arr.length > columns.length) {
                        logger.error(s"Tab characters are present in the results of your query Hive cannot cut, use Spark to do so (hive code ${realCode} 查询的结果中有\t制表符，hive不能进行切割,请使用spark执行)")
                        throw new ErrorException(60078, "Tab characters are present in the results of your query Hive cannot cut, use Spark to do so(您查询的结果中有\t制表符，hive不能进行切割,请使用spark执行)")
                      }

**Comment by xiaojie19852006** [comment]
I will fix it

**Comment by Adamyuanyuan** [comment]
Thanks，jie ge.
