### ISSUE TITLE
NullPointerException while loading udf

### ISSUE THREAD

**Issue by tinyRookie** [WeBankFinTech/Linkis#86]
![image](https://user-images.githubusercontent.com/26363549/67071676-c18b0980-f1b5-11e9-860d-990b9571e0ab.png)
When I  started a new spark engine, I encountered a nullpointerexception while loading udfs, as shown in picture above, can you help me to deal it

**Comment by tinyRookie** [comment]
![image](https://user-images.githubusercontent.com/3347292/67071947-660d4b80-f1b6-11e9-8a32-7ffa1f3eb691.png)

**Comment by peacewong** [comment]
Hello, this issue has been fixed, you can use the latest 0.9.3 version
