### ISSUE TITLE
linkis1.0.1不支持spark3.0.1版本

### ISSUE THREAD

**Issue by hzdhgf** [WeBankFinTech/Linkis#932]
使用linkis1.0.1，修改spark版本为3.0.1，编译出现错误，查找源码发现com.webank.wedatasphere.linkis.engineplugin.spark.metadata.LineageResolveLogic文件119-12行间有错误：
（1）UnresolvedRelation类没有没tableIdentifier属性。
（2）spark2.12类“InsertIntoTable”已被剔除掉。

![20210809191241](https://user-images.githubusercontent.com/29627124/128698078-ca2771e5-af6e-4e68-972d-811050635330.png)

**Comment by peacewong** [comment]
Hello, this compilation problem has been fixed in linkis 1.0.2 version
