### ISSUE TITLE
Linkis master branch compiled failed.

### ISSUE THREAD

**Issue by JYInMyHeart** [WeBankFinTech/Linkis#959]
**Describe the bug**
Linkis master branch compiled failed.

**To Reproduce**
1. Git clone master branch linkis source code into local disk.
2. Compile source code using command `mvn clean package`.
3. Building module `linkis-engineconn-plugin-loader` failed.

**Expected behavior**
Build successful.

**Desktop (please complete the following information):**
 - OS: Manjaro Linux on Windows 10 x86_64
 - Kernel: 5.10.43.3-microsoft-standard-WSL2
 - JDK: openjdk version "1.8.0_292"
 - Scala: Scala code runner version 2.13.6-20210529-211702-unknown -- Copyright 2002-2021, LAMP/EPFL and Lightbend, Inc.

**Additional context**
> [INFO] --- scala-maven-plugin:3.2.2:compile (scala-compile-first) @ linkis-engineconn-plugin-loader ---
[WARNING] Zinc server is not available at port 3030 - reverting to normal incremental compile
[INFO] Using incremental compilation
[INFO] Compiling 1 Scala source and 10 Java sources to /home/lulu/IdeaProjects/Linkis/linkis-engineconn-plugins/linkis-engineconn-plugin-framework/linkis-engineconn-plugin-loader/target/classes...
[ERROR] /home/lulu/IdeaProjects/Linkis/linkis-engineconn-plugins/linkis-engineconn-plugin-framework/linkis-engineconn-plugin-loader/src/main/java/com/webank/wedatasphere/linkis/manager/engineplugin/manager/loaders/CacheablesEngineConnPluginLoader.java:42: 错误: 找不到符号
[ERROR]         refreshablePluginCache.addRefreshListener(enginePluginInfo -> LOG.trace("Refresh engine conn plugin: [name: " + enginePluginInfo.typeLabel().getEngineType() +
[ERROR]                                                   ^
[ERROR]   符号: 类 EngineConnPluginInfo
[ERROR]
[ERROR]
[ERROR] 系统资源不足。
[ERROR] 有关详细信息, 请参阅以下堆栈跟踪。
[ERROR] java.lang.StackOverflowError
[ERROR]         at com.sun.tools.javac.comp.Resolve.isAccessible(Resolve.java:299)
[ERROR]         at com.sun.tools.javac.comp.Resolve.isAccessible(Resolve.java:355)
[ERROR]         at com.sun.tools.javac.comp.Resolve.isAccessible(Resolve.java:332)
[ERROR]         at com.sun.tools.javac.comp.Resolve.isAccessible(Resolve.java:355)
[ERROR]         at com.sun.tools.javac.comp.Resolve.isAccessible(Resolve.java:332)
[ERROR]         at com.sun.tools.javac.comp.Resolve.isAccessible(Resolve.java:355)
[ERROR]         at com.sun.tools.javac.comp.Resolve.isAccessible(Resolve.java:332)
[ERROR]         at com.sun.tools.javac.comp.Resolve.isAccessible(Resolve.java:355)
[ERROR]         at com.sun.tools.javac.comp.Resolve.isAccessible(Resolve.java:332)

**Comment by peacewong** [comment]
Hello, this is when the corresponding file is lost when the code is cloned, because the file name is too long
