### ISSUE TITLE
Linkis1.0.1&CDH6.3.2 申请资源失败

### ISSUE THREAD

**Issue by CaoYuGang** [WeBankFinTech/Linkis#977]
**Describe the bug**
Linkis1.0.1修改了相关的pom.xml（hadoop-3.0.0-cdh6.3.2，hive-2.1.1-cdh6.3.2，spark-2.4.0）重新编译安装成功，启动后执行sh bin/linkis-cli -engineType shell-1 -code "echo \"hello world\"" -codeType shell    报错

**Expected behavior**
Failed  to async(hdp-master-03:9101_0) createEngine com.webank.wedatasphere.linkis.resourcemanager.exception.RMErrorException: errCode: 110022 ,desc: Resource label: linkis-cg-engineconnmanager-hdp-master-03:9102 has no usedResource, please check, refuse request usedResource！(资源标签:linkis-cg-engineconnmanager-hdp-master-03:9102),缺少对应的资源记录，可能是该标签的资源没有初始化，请及时检查，此次申请资源失败！ ,ip: hdp-master-03 ,port: 9101 ,serviceKind: linkis-cg-linkismanager

**Comment by peacewong** [comment]
Hello, linkis 1.0.2 version has fixed the problem of host name with ‘-’
