### ISSUE TITLE
WorkSpaceException: User local root directory does not exist, please contact administrator to add

### ISSUE THREAD

**Issue by cyofeiyue** [WeBankFinTech/Linkis#98]
**BUG描述**
WorkSpaceException: User local root directory does not exist, please contact administrator to add

**复现步骤**
1. 启动后台各项项目，登陆系统
2. 点击左侧 **工作空间 or HDFS**
3. 报错：

> message: "operation failed(操作失败)s！the reason(原因)：WorkSpaceException: User local root directory does not exist, please contact administrator to add（用户本地根目录不存在,请联系管理员添加)"

4. 报错的rest接口通过浏览器控制台查看，得知是如下两个接口：
`http://xx.xx.xx.x:8080/api/rest_j/v1/publicservice/getUserRootPath?pathType=file`
`http://xx.xx.xx.x:8080/api/rest_j/v1/publicservice/getUserRootPath?pathType=hdfs`
5.确认了Linux系统:
`/tmp/linkis/hadoop`存在！
6.确认了hdfs文件系统
`/tmp/linkis/hadoop`存在！

**Comment by peacewong** [comment]
Hello, this is caused by configuration problems, you need to increase the schema, through file: // or hdfs: //
